### ISSUE TITLE
Remove `jstype=string` from `.proto` and replace `Long` with `Bigint`in js-sdk

### ISSUE THREAD

**Issue by JOOHOJANG** [yorkie-team/yorkie#1023]
**What would you like to be added**:
Remove `jstype=JS_STRING` notation from `resources.proto` and replace `Long` with `Bigint` in js-sdk
**AS-IS**
```
message ChangeID {
  ....
  int64 server_seq = 2 [jstype = JS_STRING];
  int64 lamport = 3 [jstype = JS_STRING];
  .....
}
```
**TO-BE**
```
message ChangeID {
  ....
  int64 server_seq = 2 
  int64 lamport = 3 
  .....
}
```
 
**Why is this needed**:
Currently, we're using `jstype=JS_STRING` notation in `resources.proto` due to javascript's int64 expression.
Since javascript support `Bigint`from [ES2020](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/BigInt), now we can remove `jstype=JS_STRING` notation from `resources.proto` and replace `Long` with `Bigint`.

I tested in some environments and it works well.

**Comment by Aswinr24** [comment]
Can I pick up this Issue? Would love to work on this

**Comment by Aswinr24** [comment]
So this issue basically needs two PRs right @hackerwins, one addressing the ```jstype=string``` issue in this main repository and the other related to replacing ```long``` with ```BigInt``` for the yorkie js-sdk repository ?
