### ISSUE TITLE
Delete a node from a heap by in-place way

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#105]
[PriorityQueue.Release](https://github.com/yorkie-team/yorkie/blob/master/pkg/pq/priority_queue.go#L53) was intended to delete the given node from the heap. It was difficult to find and delete the target node from the heap, so we added all nodes to the new heap excluding that node.

And @mojosoeun introduced [a way to delete in-place](https://github.com/yorkie-team/yorkie-js-sdk/pull/101#discussion_r525808950) in the JS SDK. It turns out that deleting a node from a heap in-place way is easier to solve than we thought.

I would like to Go to introduce this method as well.

For more about deleting a node from a heap:
  http://www.mathcs.emory.edu/~cheung/Courses/171/Syllabus/9-BinTree/heap-delete.html

**Comment by ppeeou** [comment]
Could I try this issue?

**Comment by hackerwins** [comment]
@ppeeou Sure.
