### ISSUE TITLE
Add increase operation for number types to use as a counter

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#12]
Increase operation is an operation that can be used when implementing functions such as the Facebook Like button. We can also use Increase operation as Decrease operation if we handle negative values. 

The following are examples of APIs provided to users.

```go
err = doc.Update(func(root *proxy.ObjectProxy) error {
	root.SetInteger("age", 36)
	root.GetInteger("age").Increase(1)
	return nil
}, "The day after your birthday")
```

The operation is relatively easy to implement because there is no conflict between operations created between different clients. And I think implementing Increase operation will help you understand Yorkie's overall data flow.

It would be helpful to refer to other operations to implement the operation.
https://github.com/yorkie-team/yorkie/tree/master/pkg/document/operation

**Comment by dc7303** [comment]
@hackerwins Could I try this issue?

**Comment by hackerwins** [comment]
@dc7303 👍 Sure.

**Comment by dc7303** [comment]
I am currently trying to implement increase operation for Integer, Long and Double types.  
And for this, I am trying to implement a proxy type like 'NumberProxy'.  
Could you let me know if this is what I should be doing?

**Comment by hackerwins** [comment]
@dc7303 Great! You are already trying to make a second contribution.
I haven't understood NumberProxy yet. Are you trying to introduce it to eliminate duplicate code?
How about starting with a simple PR?
