### ISSUE TITLE
what's the license?

### ISSUE THREAD

**Issue by kapilt** [yorkie-team/yorkie#14]
its unclear what license this project uses

**Comment by hackerwins** [comment]
@kapilt Thank you for your interest.

This project is the initial stage. For now, we have not decided which license to choose. We will discuss and decide with the people working on the project together.

**Comment by 094459** [comment]
It is probably worth noting that until it has a license, it is not open source so you may struggle to get contributors or build a community.

**Comment by hackerwins** [comment]
@kapilt @094459 
Thanks for the feedback. We choose the Apache License 2.0.
https://github.com/yorkie-team/yorkie/blob/master/LICENSE
