### ISSUE TITLE
Add flags that can set all configurations of Agent

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#152]
**What would you like to be added**:

Currently, users can only set the configurations by passing the [config file flag](https://yorkie.dev/docs/main/commands)(`-c`). We need to add flags to [agent cmd](https://github.com/yorkie-team/yorkie/blob/main/pkg/cli/agent.go#L116) so that we can set all the configurations of the agent individually.

**Why is this needed**:

It would be convenient if users could directly set the agent's configuration as flags in a deployment environment such as Docker Compose or Kubernetes.

**Comment by computerphilosopher** [comment]
Could I try this issue?

**Comment by dc7303** [comment]
@computerphilosopher sure 👍 
Do you know good practices? If there is, please recommend it.

I've looked for examples that are good at managing command options. And I can see that [etcd](https://github.com/etcd-io/etcd) manages the command options well. So I think it's a good idea to follow the practice of `etcd`.
What do you think? Please tell me your ideas :)

**Comment by computerphilosopher** [comment]
In my opinion, Each command-line argument key should similar to the equivalent key of the configuration file to prevent confusion.

The existing configuration file has a two-level format.

https://github.com/yorkie-team/yorkie/blob/6b1c9bcb32c0f853e19c343afffe2bdf79fdbba9/yorkie/config.sample.json#L1-L25

My idea is composing command line argument by {first_level_key}-{second_level_key} format. all characters of keys are the lower case.

Let me give you an example. we can convert the sample json file to command line arguments like this

```
-rpc-port=11101 -metrics-port=11102 -mongo-connectiontimeoutsec=5 ....
```

if json's value is a list, the command-line argument's value will be comma separated string.
```
etcd-endpoints=localhost:2379,localhost:2380,localhost:2381
```

If a configuration file is provided, other command-line flags and environment variables will be ignored like [etcd's policy](https://etcd.io/docs/v3.4.0/op-guide/configuration/). (The etcd can be configured by environment variables too. but it's not the point of this issue.) 

There are some use cases of the '--' separator like a kubectl command. 

```kubectl exec kubectl exec --stdin --tty shell-demo -- /bin/bash```

I'm not sure yorkie agent command will use this form in the future. but it will be good if can have an extendable design.

**Comment by hackerwins** [comment]
@computerphilosopher Thanks for the reply.

[etcd](https://github.com/etcd-io/etcd/blob/master/etcdctl/ctlv3/command/member_command.go#L33) and [kubectl](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/get/get.go#L155) are implementing the CLI using [Cobra](https://github.com/spf13/cobra) like [us](https://github.com/yorkie-team/yorkie/blob/main/pkg/cli/agent.go#L40). And both look to follow [GNU's Standards for Command Line Interfaces](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html).


I think we can treat flags with the same pattern.
```
--rpc-port=11101 --metrics-port=11102 --mongo-connection-timeout=5s ....

or

-p=11101
```

**Comment by computerphilosopher** [comment]
We can define both short and long argument by Cobra like many projects. But If we decide to define short arguments, we should discuss what characters will be assigned for each configuration. 

I would like to propose short and long flags like the following. 

```
--rpc-port: -p
--rpc-cert-file: -f
--rpc-key-file: -k

--metrics-port: -m

#In my opinion, inserting a dash('-') before the letter that is capital in a configuration file is much readable.
#It is a more conventional way to convert the camel-case to the snake-case.
--mongo-connection-timeout-sec: -t
--mongo-connection-uri: -u
--mongo-yorkie-database: -d
--mongo-ping-timeout-sec: -P

--etcd-endpoints: -e
--backend-snapshot-threshold: -s
--backend-snapshot-interval: -i
```

Unavoidably, arbitrary characters are assigned for some configurations. For example, Short flag '-p' is used for a 'port' conventionally. but agent command has two configurations about port, '--rpc-port' and '--metrics-port'.  we have to select which configuration takes '-p', and assign another flag for the remainder.

**Comment by hackerwins** [comment]
@computerphilosopher 
Short flags are often used or useful for defining common flags. I think it's okay to define all flags as long flags first then short flags in the future.

**Comment by computerphilosopher** [comment]
@hackerwins 
Okay. I will implement long flags first.

**Comment by hackerwins** [comment]
@computerphilosopher
I don't think the test codes are efficient for this part. I think it would be nice to proceed without test codes for flags.
