### ISSUE TITLE
Improve Peer Awareness's metadata to be updatable

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#153]
**What would you like to be added**:

Realtime collaborative editors usually need to propagate volatile data, such as cursor position to other peers. This type of data needs to be propagated, but not stored.

For now, we implemented [Peer Awareness](https://github.com/yorkie-team/yorkie/blob/main/design/peer-awareness.md) to propagate the metadata of the client, but updates are not possible. We can cover this scenario by improving the Peer Awareness's metadata so that it can be updated.

**Why is this needed**:

The cost of storing data is expensive, so it is economical to propagate this type of data but not store it.

**Comment by dc7303** [comment]
@hackerwins could I try this issue?

**Comment by hackerwins** [comment]
@dc7303 Yes. of course. This issue is more complicated than other issues, so writing a design document together would be nice.

**Comment by hackerwins** [comment]
`Metadata` for the purpose of sharing the status of peers who are watching the document together is stored in the `SubscriptionMap` as non-persistent data.

Since the client receives Peer's changes using `Watch` stream, it would be good to implement updating metadata using this stream as well. However, [gRPC-web](https://github.com/grpc/grpc-web/blob/master/doc/streaming-roadmap.md#full-duplex-streaming-over-http) does not support bi-directional streams now.
