### ISSUE TITLE
Change `XXXTimeoutSec` flags in CLI to duration

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#168]
**What would you like to be added**:

Change `XXXTimeoutSec` flags in CLI to duration so that users can input the flags in `5s` or `5m`.

https://github.com/yorkie-team/yorkie/blob/120075576a431de3382740ec1844948ff16177bb/pkg/cli/agent.go#L50-L51

```
# AS-IS
yorkie agent --mongo-connection-timeout-sec 60

# TO-BE
yorkie agent --mongo-connection-timeout 1m
```

We can easily convert it using [ParseDuration](https://golang.org/pkg/time/#ParseDuration).

**Why is this needed**:
- Users can set durations in flags more conveniently.

**Comment by computerphilosopher** [comment]
If we set flags to [DurationVar](https://golang.org/src/flag/flag.go?s=27461:27543#L809), we can use duration string as a flags' value.

But I don't use it in #152 because flags' names are 'second', not 'duration'.

**Comment by hackerwins** [comment]
@computerphilosopher Yes of course. We have to change it.

**Comment by dc7303** [comment]
I was distracted the other day and couldn't take care of it.
I will proceed!
