### ISSUE TITLE
Build binaries for environments when releasing a new version

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#175]
**What would you like to be added**:

Build binaries for environments when releasing a new version.

- yorkie-v0.1.4-darwin-amd64.zip
- yorkie-v0.1.4-linux-amd64.tar.gz
- yorkie-v0.1.4-linux-arm64.tar.gz
- yorkie-v0.1.4-linux-ppc64le.tar.gz
- yorkie-v0.1.4-windows-amd64.zip

etcd seems to build with [this script](https://github.com/etcd-io/etcd/blob/master/scripts/build-binary).

**Why is this needed**:
- Users can download and use Yorkie without building for their environment.

**Comment by computerphilosopher** [comment]
It seems we can release binary automatically with some github action.

https://github.com/marketplace/actions/github-action-publish-binaries
