### ISSUE TITLE
Add PermissionDenied error response to authorization webhook

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#205]
**What would you like to be added**:
Add `PermissionDenied` response to Authorization webhook response error.
I think it would be good to talk about the spec.
issue starting point: https://github.com/yorkie-team/yorkie/pull/203#discussion_r662523173

**Why is this needed**:
This is to distinguish between Unauthenticated and PermissionDenied responses.

**Comment by dc7303** [comment]
@hackerwins Could I try this issue?

**Comment by hackerwins** [comment]
@dc7303 Of course!

**Comment by hackerwins** [comment]
Both authentication and authorization checks should be performed by the external auth server. 

In the case of Yorkie Server, there is a need to receive "unauthenticated" and "permission denied" responses from the Auth server and send them to the client. If the token of the client is not authenticated, the client can retry the request after acquiring a new token. However, if the client doesn't have permission to the request, they cannot retry.

Currently, only the `unauthenticated` status code is being passed from Yorkie server. There was a consideration of whether to explicitly pass `PermissionDenied` in the status code when the Auth server determines the lack of permissions.
