### ISSUE TITLE
Validate the entire setup configuration

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#206]
https://github.com/yorkie-team/yorkie/blob/6eccd481eb74fc90b0d041a56280c129d43e2675/internal/cli/agent.go#L69-L71

**What would you like to be added:**
Option values ​​that need validation should be fully checked. After the check, if there is a problem, the agent can stop the execution and ask the user to fix it.

**Why is this needed:**
We need to validate the options entered by the user to prevent them from being executed incorrectly.

**Comment by wonjerry** [comment]
Can I get this issue? I am trying to work with etcd config, validate endpoint length, username, password empty

**Comment by hackerwins** [comment]
@wonjerry Yes of course.

**Comment by hackerwins** [comment]
It would be good to add only Validation for Metrics and close the issue.
https://github.com/yorkie-team/yorkie/blob/188fb32f498b0c162ab3415e7cbf5c092a1b048b/yorkie/config.go#L93-L112
