### ISSUE TITLE
Fix warnings when running `make lint`

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#226]
**Description**:

It seems that some libraries used by golangci-lint have been deprecated. Check the suggested way in the warning message to solve the issue.

```
$ make lint
golangci-lint run ./...
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.
```

**Why**:

- Keep our repositories clean.

**Comment by blurfx** [comment]
If no one is investigating at this issue,  I'd like to fix this.

**Comment by blurfx** [comment]
After doing some research I believe `golint` can be replaced with [`revive`](https://github.com/mgechev/revive).

But `interfacer`, It seems to me there is no good alternative. I couldn't find a project similar to it.

So I think we need to decide whether to continue using it or remove it.

**Comment by hackerwins** [comment]
@blurfx Thanks for the research. Then it would be good to work like below.

1. Replace `golint` with `revive`
2. Remove `interfacer`
