### ISSUE TITLE
Remove garbage subscriptions after agent stopped ungracefully

### ISSUE THREAD

**Issue by umi0410** [yorkie-team/yorkie#229]
**What would you like to be added**:

This issue was introduced in a commit of PR #214.
In `yorkie/backend/sync/etcd/pubsub.go`
```
// TODO(hackerwins): If the agent is not stopped gracefully, there may
// be garbage subscriptions left. Consider introducing a TTL and
// updating it periodically.
```
**Why is this needed**:

I guess if connections don't terminate gracefully, agents won't be able to invoke `Coordinator.Unsubscribe()` method so there can be some garbage subscriptions.

I opened this issue because this existed in the code as `TODO` but no issue was written.

**Comment by umi0410** [comment]
I'm interested in this issue! :smiley:

**Comment by umi0410** [comment]
I wrote some memo to explain this issue.
![image](https://user-images.githubusercontent.com/33250725/130317305-8bb65f28-5124-4211-9eb2-c03a5edca30a.png)

There is one `yorkie` and two clients subscribing the same document so there is two subscription data in etcd and clients can see there is two users in GNB(Global Navigation Bar).

```
# First, I set my environment by docker-compose
$ docker-compose -f docker/docker-compose-my-debug.yml up --build
...
# Next, I killed the yorkie container.
$ docker rm -f docker_yorkie_1      
# Next, I re-run the yorkie container.            
docker_yorkie_1
$ docker-compose -f docker/docker-compose-my-debug.yml up --build
...
```

After removing the container ungracefully, creating the container and refreshing the browsers, we can see there are 4 users and 4 subscriptions now.
![image](https://user-images.githubusercontent.com/33250725/130317411-6705a5d4-df58-4d70-9e5c-fd93727de473.png)

This proves grabage subcriptions can exist due to ungraceful shutdown.

**Comment by umi0410** [comment]
@hackerwins I examined this issue and am considering how to fix it. Can you suggest me some guides?

**Comment by hackerwins** [comment]
We replaced etcd-based clusters with sharding-based clusters. So this issue can be closed.
