### ISSUE TITLE
How about adding the ETCD.enable option?

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#232]
**What would you like to be added**:
I was improving the ETCD config by referring to the [issue comments of yorkie#230](https://github.com/yorkie-team/yorkie/pull/230#discussion_r689562829).
Come to think of it, we are configuring ETCD activation by checking if `config.ETCD` is nil.

So, the cluster mode setting is specified by giving the ETCD option through the config json file. And unfortunately, cluster mode cannot be set with command options due to these structural limitations.

I would like to suggest an enable option like Mattermost's `ClusterSettings.Enable` option.
refernce:
1. https://docs.mattermost.com/scale/high-availability-cluster.html#configuration-settings
2. https://docs.mattermost.com/configure/configuration-settings.html#enable-high-availability-mode

How about we also add an option `ETCD.enable` to decide whether to enable it or not?

**Why is this needed**:
Here are the benefits I thought of with this improvement:
1. The user can add the ETCD option to the configuration file in advance and enable or disable the high availability mode through the enable value.
2. ETCD options can be added as command options.
3. From a development point of view, option-related code can be managed in a pattern consistent with other options. (e.g validation, setting default values, etc.)

**Comment by hackerwins** [comment]
Thanks for the good comments. It is good to think about how the user should input to set the cluster mode using the flags of the CLI.

Does the interface you suggested look like below?

With `config.json`:
```bash
yorkie agent -c config.json

{
  ...
  ETCD: {
    Enable: true,
    Endpoints: ["localhost:2379"]
  }
}
```
```

With flags:
```bash
yorkie agent --etcd-enable true --etcd-enpoints localhost:2379
```

**Comment by dc7303** [comment]
@hackerwins Yes, that's right.

**Comment by dc7303** [comment]
Is @wonjerry currently working on adding the enable configuration?
If it is true, I will proceed with the [issue comments of yorkie#230](https://github.com/yorkie-team/yorkie/pull/230#discussion_r689562829) after this work is finished.

This is because, if ETCD Config is not always nil, the default value management method can be written similarly to other configs.

**Comment by hackerwins** [comment]
@wonjerry, @dc7303 
This issue needs to be discussed on how to define the settings.

@wonjerry Please don't start implementing it yet.

**Comment by wonjerry** [comment]
Okay I haven't started implementing it yet.

**Comment by dc7303** [comment]
@hackerwins I think we can close this issue for now.
Looking at the cases, it seems that not many services are using `enable'.
So it might be good to think about it again later when there is user feedback.

**Comment by hackerwins** [comment]
@dc7303 Thanks for the reply.
