### ISSUE TITLE
Add trylock method to memory locker

### ISSUE THREAD

**Issue by wonjerry** [yorkie-team/yorkie#234]
**What would you like to be added**:
trylock method of etcd was added in version 3, and it is required in [packs.go](https://github.com/yorkie-team/yorkie/blob/ad561634dcf40c04c47f3d57eb7eb85482a45405/yorkie/packs/packs.go#L117).

**Why is this needed**:

So, 
1. update etcd to v3
2. add trylock method to etcd/locker.go
3. use trylock in [packs.go](https://github.com/yorkie-team/yorkie/blob/ad561634dcf40c04c47f3d57eb7eb85482a45405/yorkie/packs/packs.go#L117).

**Comment by wonjerry** [comment]
Trylock has been added to etcd version 3.5, but only version 3.3 has been distributed to [pkg.go.dev](https://pkg.go.dev/go.etcd.io/etcd?tab=versions), so hold it for a while.

**Comment by wonjerry** [comment]
https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.5.md#package-clientv3

**Comment by hackerwins** [comment]
We can use etcd 3.5 version. #274
Next, it seems that we need to complete the try lock implementation for the memory.

**Comment by wonjerry** [comment]
Oh okay I'll start implementing

**Comment by hackerwins** [comment]
@wonjerry The etcd version is implemented in #274. Please review the PR.
It would be good to continue working with the memory version.

**Comment by wonjerry** [comment]
After researching a bit, I found that the go's built-in library, sync, [added the trylock function](https://github.com/golang/go/issues/45435) in version 1.18, and I am going to try to use this function in the memory version by increasing the go version.

Can I try to increase version of go in yorkie to 1.18?

**Comment by wonjerry** [comment]
Oh, the [stable version is still 1.17.3](https://github.com/golang/go/tags). I'll try it when the stable 18 version comes out..

**Comment by hackerwins** [comment]
@wonjerry Thanks for your research. It looks like we can get this done soon without stress. 👍
