### ISSUE TITLE
QEMU bug on apple m1 chip

### ISSUE THREAD

**Issue by xoxwgys56** [yorkie-team/yorkie#245]
**What happened**:
When launch `yorkie` project using `yorkieteam/yorkie` image. got error about `qemu` like below.

```sh
yorkie  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

this is known issue on `QEMU` and I can not find how to resolve. but I attached related urls.

**What you expected to happen**:
`yorkie` work properly.

**How to reproduce it (as minimally and precisely as possible)**:
referenced [this issue](https://gitlab.com/qemu-project/qemu/-/issues/340) which gitlab, `QEMU`'s original repository.  
**Rechardson Dx** said try to edit `dockerfile` and `docker-compose`. I do not tested.

**Anything else we need to know?**:
I attached related urls below

 - [QEMU issue](https://gitlab.com/qemu-project/qemu/-/issues/340)
 - [stackoverflow answer about qemu](https://stackoverflow.com/questions/68862313/qemu-uncaught-target-signal-11-segmentation-fault-core-dumped-in-docker-con)

**Environment**:
- Operating system: OSX Big Sur 11.5.2 apple m1
- Browser and version: chrome, safari
- Yorkie version (use `yorkie version`): 0.1.6 
- Yorkie JS SDK version: 0.1.6

**Comment by xoxwgys56** [comment]
I found solution.  

Follow [this article](https://dev.to/lakhansamani/create-docker-image-on-apple-silicon-m1-mac-2f75), he said add `--platform linux/amd64` flag when build image. Our issue occurred on silicon mac, I build image with `--platform linux/arm64` flag and it works.

But after this, I do not know how to apply for `yorkie` image.   
I think just add `--platform linux/arm64` is not a good solution, I suggest add `arm64` tag for docker image.  

@hackerwins, Could you share your opinion about this?

**Comment by hackerwins** [comment]
@xoxwgys56 Thanks for your searching.
I added a platform flag when changing instances in Yorkie cluster from t2.micro(x86_64) to t4g.small(arm64). I pushed the latest image with arm64 as well. Can you please check if the problem still occurs in the image tagged `latest`?

**Comment by xoxwgys56** [comment]
@hackerwins I am sorry what I did not check about that.
Like you said. now work properly on m1 Monterey.  

So this issue gonna be closed. Thanks for your reply again.
