### ISSUE TITLE
Reduce latency like figma to impove user experience

### ISSUE THREAD

**Issue by lohnsonok** [yorkie-team/yorkie#247]
**What would you like to be added**:
Simply reduce the synchronization latency even more like on figma
**Why is this needed**:
User experience is crucial when using or creating real-time collaboration and very low latency is required.

**Comment by hackerwins** [comment]
Hello. Thanks for the issue report.

When you tested the Yorkie, I think the latency was relatively long compared to Figma. I have a few questions for you to improve Yorkie.

- In what environment did you test it?
- Do you have any references or ideas to improve Yorkie?

**Comment by hackerwins** [comment]
Thanks for the link. It seems to help improve document editing performance.

A while ago I saw a connection from Benin in the CodePair service log. I thought that the latency you reported might be a problem with the distance to the Agent server in Seoul.

**Comment by lohnsonok** [comment]
> Thanks for the link. It seems to help improve document editing performance.
> 
> A while ago I saw a connection from Benin in the CodePair service log. I thought that the latency you reported might be a problem with the distance to the Agent server in Seoul.

Ok I'm will retry and retest performance. Thank you 
If you have any document link to learn how to use and understand data types directly in any languages. I will be helpful and benefit for me.

**Comment by hackerwins** [comment]
This issue has been open for a while, and as we haven't been able to find specific improvement ideas, I will now close it. Let's recreate it when necessary.
