### ISSUE TITLE
Rename Agent to Server

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#260]
**Description**:

Replace `Agent` with `Server` in the Yorkie project.

Initially, I wanted to install Yorkie on the nodes where MongoDB is installed, so I named it `Agent`.

However, we implemented Agents like normal Servers, and the name of `Agent` is confusing, so it would be better to rename it as `Server`.

**Why**:
- Increase the readability of our project.

**Comment by AkiaCode** [comment]
Can I try this issue?
