### ISSUE TITLE
Research vtprotobuf

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#269]
**Description**:

Introduce vtprotobuf and measure performance change in Agent.

This summer, the Vitess teams have posted [an article about their protobuf generator](https://vitess.io/blog/2021-06-03-a-new-protobuf-generator-for-go/ ) with impressive benchmarks. It is worth further examining whether there is a performance gain when introducing [vtprotobuf](https://github.com/planetscale/vtprotobuf).

**Why**:
- gogo protobuf is [looking for maintainers](https://github.com/gogo/protobuf/issues/691), which can cause problems in maintenance in the long term.

**Comment by gedw99** [comment]
vtprotobuf is pretty cool. I have been using the DRPC with it.  Its really awesome ...

can compile the golang code to wasm and its works to talking to the server. so then your golang client code is reusable across web, mobile, desktop.

here is an example using DRPC and wasm fully
https://github.com/lightninglabs/falafel#generating-jsonwasm-stubs

**Comment by hackerwins** [comment]
We are attempting to change the existing RPC using connect-rpc.

https://github.com/yorkie-team/yorkie-js-sdk/issues/375
