### ISSUE TITLE
Add admin commands

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#273]
**Description**:

Add admin commands.

Let's implement admin commands, starting with finding and deleting documents.

```bash
# starts server
$ yorkie server
INFO	default	backend created: id: ca81i5jhkdflkq76edr0, rpc: localhost:11103: db: memory
INFO	default	serving profiling on 11102
INFO	default	serving RPC on 11101
INFO	default	serving admin on 11103

$ yorkie --admin-addr localhost:11103 document describe <doc-key>
$ yorkie --admin-addr localhost:11103 document rm <doc-key>
```

Task
- [x] Create project: `yorkie project create <name>`
- [x] List projects: `yorkie project ls`
- [x] History: `yorkie history <project_name> <document_key>`
- [ ] List documents: `yorkie document ls <project_name>`
- [ ] Remove project: `yorkie project rm <name>`
- [ ] Remove document: `yorkie document rm <project_name> <document_key>`

**Why**:

- Users can manage documents or projects using CLI.

**Comment by zacscoding** [comment]
can i try this issue? 🙇  cc. @dc7303
