### ISSUE TITLE
Add `--log-level` flag to agent command.

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#279]
**Description**:

Add `--log-level` flag to [agent command](https://github.com/yorkie-team/yorkie/blob/main/internal/cli/agent.go).

Configures log level with `debug`, `info`, `warn`, `error`, `panic`, or `fatal`.

**Why**:

- We can configure the log level on starting the agent.

**Comment by zacscoding** [comment]
Could i try this issue? :)
