### ISSUE TITLE
Write Github CI script to test according to environment

### ISSUE THREAD

**Issue by AkiaCode** [yorkie-team/yorkie#293]
**What would you like to be added**:
Workflow that automatically tests according to the environment (windows, ubuntu, macOS) when PR comes in.

**Why is this needed**:
It's easy to manage PR effectively because the maintainer can't run it and test it, depending on the environment.

**Comment by Limm-jk** [comment]
Can I try this issue? 
I don't know if it's correct you want, but I think, it's easy to solve.

**Comment by Limm-jk** [comment]
I cancel this opinion. When the test environment update, I need to think about how to write each coverage on PR.

**Comment by hackerwins** [comment]
It doesn't seem necessary to test all the different development and execution environments at the moment. Let's recreate it when needed.
