### ISSUE TITLE
Add Yorkie to Chocolatey, Winget

### ISSUE THREAD

**Issue by AkiaCode** [yorkie-team/yorkie#294]
**What would you like to be added**:
https://docs.microsoft.com/ko-kr/windows/package-manager/package/
https://docs.chocolatey.org/en-us/features/create-packages

**Why is this needed**:
To make it easy for Windows users to use

**Comment by hackerwins** [comment]
Currently, I don't feel the need to support Chocolatey. Let's recreate it when needed.
