### ISSUE TITLE
Question about Remove method of RHT and RHTNode

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#298]
https://github.com/yorkie-team/yorkie/blob/5556157a8542cc113cfafb4e2962fe608eb1d035/pkg/document/json/rht.go#L43-L48

https://github.com/yorkie-team/yorkie/blob/5556157a8542cc113cfafb4e2962fe608eb1d035/pkg/document/json/rht.go#L119-L127

The above two codes do not check if the RHTNode has already been cleared. Is this the intended behavior?

If you call Remove again with a ticket after it has been deleted through RHT.Remove, you can get the value of that node. I think this behavior could potentially cause bugs.

**Comment by hackerwins** [comment]
Thanks for the question. However, I still don't understand the intent and concern of the question.

**Comment by dc7303** [comment]
I got feedback from @hackerwins, and I'll log it. And close the issue.

1. The issue of being overwritten when removedAt is called multiple times
- This is intended behavior. When deleting the same character on different peers, the intention is to leave the final deletion time. Last write wins (LWW)
> Last write wins (LWW):
A timestamp is attached to each update, and updates with higher timestamps always overwrite values written by updates with lower timestamps. However, if a replica has already applied an update with a higher timestamp, and it subsequently receives an update with a lower timestamp, the latter update is ignored. This approach is one way of ensuring convergence.

2. The issue of marking removedAt and not deleting the value
- This seems to have to be removed first. There doesn't seem to be any reason at this time to have a value in an unnecessarily deleted state. (It may be necessary when developing UNDO/REDO, but it is better to think about it again when developing UNDO/REDO)
