### ISSUE TITLE
Authentication WebHook looks unimplemented

### ISSUE THREAD

**Issue by zyuiop** [yorkie-team/yorkie#355]
**What happened**:

I tried to configure an authentication webhook following instructions from https://yorkie.dev/docs/auth-webhook.

```bash
# Attempt 1: use the command line flag
docker run --name yorkie --rm --network host yorkieteam/yorkie:0.2.9 server --authorization-webhook=http://localhost:5000/yorkie/webhook


# Attempt 2: use a configuration file
docker run --name yorkie --rm --network host -v (pwd)/yorkie_config.yaml:/yorkie_config.yaml yorkieteam/yorkie:0.2.9 server -c /yorkie_config.yaml
```

Output of the first attempt: 

```
Error: unknown flag: --authorization-webhook
```

Output of the second attempt: normal, but the endpoint is not called when sending `AttackDocument` on the RPC port.

Config used in the second attempt (extract):

```yaml
Backend:
  AuthWebhookURL: "http://localhost:5000/yorkie/webhook"
```

**What you expected to happen**:

 - I expected the command line argument to work (`--auth-webhook=xxx` did not work either)
 - I expected the RPC server to try calling (or fail with some logs) my webhook endpoint when calling AttachDocument over RPC

**How to reproduce it (as minimally and precisely as possible)**:

Run `docker run --name yorkie --rm --network host yorkieteam/yorkie:0.2.9 server --authorization-webhook=http://localhost:5000/yorkie/webhook`

Alternatively, copy the default config file, set a webhook URL, and start the server. Then, try to use a RPC client (for example, the Go one) and send an AttachDocument command.

**Anything else we need to know?**:

I generated Python stubs from the Protobuf/GRPC files and used GRPC in python to test.

**Environment**:
- Operating system: ArchLinux // Docker container
- Browser and version: None
- Yorkie version (use `yorkie version`): v0.2.9
- Yorkie JS SDK version: None

Thanks!

**Comment by dc7303** [comment]
Thank you for reporting the issue! 👍 
There has been a recent change to the Yorkie structure, and the guide update has been a bit delayed. 🙏 

Now we can apply auth-webhook on a per-project basis. (ref: #313)
There is no CLI command yet, and we need to add it.

Currently, you can easily add your auth-webhook URL via [yorkie-house](https://github.com/yorkie-team/yorkie-house).

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/40932237/178133399-2e0ef2ed-c666-49d5-a008-9f91896d8bb8.png">

**Comment by jeonjonghyeok** [comment]
@zyuiop 
development is complete.
Please confirm and close issue 😃

**Comment by hackerwins** [comment]
The documentation should also be updated.
https://yorkie.dev/docs/auth-webhook

**Comment by jeonjonghyeok** [comment]
Sure. I will also update the doc

**Comment by zyuiop** [comment]
The documentation appears to have been updated, and the problem fixed, so I'm closing the issue. Thank you for your work!
