### ISSUE TITLE
Need to add auth-webhook-url registration command

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#358]
**Description**:
There are reports of difficulties registering with the auth-webhook-url. (in #355)
Users should be able to manage auth-webhook-url by project unit through CLI as well.

Design example: `yorkie project update [flag(--auth-webhook-url)] [project_name] [value]`

- [ ] Add command
- [ ] Update document

**Why**:
The user should be able to manage auth-webhook-url through the CLI command.

**Comment by jeonjonghyeok** [comment]
@hackerwins  Could I try this issue?
cc : @dc7303 @ppeeou

**Comment by hackerwins** [comment]
@jeonjonghyeok Sure. If you have any questions, feel free to comment here.

**Comment by jeonjonghyeok** [comment]
Sure~

**Comment by jeonjonghyeok** [comment]
@hackerwins  I have a question

update the project by calling admin
I need to set a field called type.ID
But I don't know what id means here.

If it is the ID of the person who updated it, is there any problem if I receive it as a command?

**Comment by hackerwins** [comment]
@jeonjonghyeok Sorry for the late answer.

The `ID` of `UpdateProject` API means project ID. On the web(Yorkie House), it was a situation where we could receive the Project from the server and then update it with ID. 

https://github.com/yorkie-team/yorkie-house/blob/main/src/features/projects/projectsSlice.ts#L45

However, in CLI, I think that it is a situation where we need to update a field using `name` directly. So I think it is good to change UpdateProject API from `id`-based to `name`-based.
