### ISSUE TITLE
Change the data type of data inserted into the db from uint64 to int64.

### ISSUE THREAD

**Issue by chromato99** [yorkie-team/yorkie#373]
**Description**:

https://github.com/yorkie-team/yorkie/pull/370#discussion_r931726563

It would be better to change uint64 to int64 among data types that are inserted into db.
For example, the data type of ServerSeq defined in `pkg/document/change/checkpoint.go` need to change from uint64 to int64. 

**Why**:

https://pkg.go.dev/go.mongodb.org/mongo-driver/bson#hdr-Native_Go_Types

According to the above document, uint64 is marshaled to int64, when marshalling a D or M to BSON.
Therefore, there is no problem in the case of a number smaller than math.MaxInt64 even now, however changing this can make the data types more consistent.

**Comment by hackerwins** [comment]
This was fixed by https://github.com/yorkie-team/yorkie/pull/381
