### ISSUE TITLE
Error when building Docker images with Go 1.19

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#378]
**Description**:

Error when building Docker images with Go 1.19

https://github.com/yorkie-team/yorkie/runs/7644025991?check_suite_focus=true

To avoid the error, we decided to fix the version to 1.18.

**Why**:
- We should support Go 1.19 in the future.

**Comment by andig** [comment]
This blocks the brew package build: https://github.com/Homebrew/homebrew-core/pull/107165

**Comment by hackerwins** [comment]
@andig Thanks for letting me know.

**Comment by blurfx** [comment]
It seems to be resolved in the [Go 1.19.2 release](https://github.com/golang/go/issues?q=milestone%3AGo1.19.2+label%3ACherryPickApproved). It would be good to try building with 1.19.2.

**Comment by hackerwins** [comment]
@blurfx Thanks for letting me know.

**Comment by andig** [comment]
@hackerwins please don't forget to unpin Go version in the homebrew repo

**Comment by hackerwins** [comment]
@andig Thanks. I will unpin it when we release the next version.
