### ISSUE TITLE
Suggest improvement of issue template

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#383]
**What would you like to be added**:
The attached image is the page I accessed to write bug-report on ETCD.
How about we change it like this to improve usability?

references:
 - [Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
 - [ETCD's bug-report template](https://github.com/etcd-io/etcd/blob/main/.github/ISSUE_TEMPLATE/bug-report.yaml)

Image:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/40932237/183243840-c25e2471-ab76-4e55-b0a9-77c5cf0948f1.png">

**Why is this needed**:
It provides more convenient usability to users who create issues.

**Comment by hackerwins** [comment]
Thank you for your reporting.

If you have any suggestions on the content or format that should be included in the issue template, please feel free to submit a PR. We can discuss it together and make further improvements.

**Comment by hackerwins** [comment]
For now, I'll close this. If you are still interested in this issue, please open it again.

**Comment by krapie** [comment]
Many other open source projects use this `yaml` based templates for better accessibility.
It will be good to introduce new `yaml` based templates for both issue & PR before Yorkie becomes v1.0.
