### ISSUE TITLE
Collect Worker Count Metric that Runs Through the Background Package

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#386]
**What would you like to be added**:
https://github.com/yorkie-team/yorkie/blob/d0165307ad35dd0a11655841b3628c6b6b94dba4/server/backend/background/background.go#L45

I think you can try to collect the count of workers running in the background package.

**Why is this needed**:
You can know ahead of time when to process many workers. This can prevent problems that may arise from this.

**Comment by hackerwins** [comment]
Thank you for reporting. It would be helpful to examine these metrics. Feel free to submit a PR.

**Comment by kokodak** [comment]
I'm interested in this issue, would the following rough approach be correct?

1. have a counter in the `AttachGoroutine()` method to record when the goroutine starts or ends.
2. collect counter metrics to show a monitoring tool like Prometheus how many goroutine workers are running in the background.

**Comment by krapie** [comment]
@kokodak Yes. I will assign you on this issue 👍
