### ISSUE TITLE
bou.ke/monkey is problematic in ARM environment

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#388]
**What would you like to be added**:
I noticed an issue while using `bou.ke/monkey` while reviewing #370. ([see](https://github.com/yorkie-team/yorkie/pull/370#discussion_r939628936))

I found out that there was an issue when using the `monkey.PatchInstanceMethod` function in the m1 pro MacBook environment.
```bash
$ go test -tags integration -race ./test/integration/main_test.go ./test/integration/history_test.go -v
# bou.ke/monkey
../../../go/pkg/mod/bou.ke/monkey@v1.0.2/replace.go:24:14: undefined: jmpToFunctionValue
FAIL	command-line-arguments [build failed]
```

It can be solved by adding `GOARCH=amd64` environment variable, but I am not sure if this is a perfect solution.

Currently bou.key/monkey is in an archived state.
Seeing that other projects in 2018 experienced the same issue, it is judged that it will not be resolved. (refer: jenkins-x/jx#2081)

We should consider looking for other libraries or using the GOARCH environment variable.

**Why is this needed**:
Tests written in a non-ARM environment can cause problems in an ARM environment.

**Comment by hackerwins** [comment]
Related with https://github.com/yorkie-team/yorkie/pull/299.

**Comment by hackerwins** [comment]
We've used GOARCH before to handle this issue.
If you think of a better way, please comment again.

**Comment by markelog** [comment]
Had the same issue in my pkg, I just forked the monkey pkg and added support for m1 – https://github.com/markelog/monkey. Since original repo is archived already, it seems forking is fine as tmp measure
