### ISSUE TITLE
gRPC error code 12 (unknown service) on envoy - yorkie

### ISSUE THREAD

**Issue by Krapi0314** [yorkie-team/yorkie#390]
**What happened**:
Cannot communicate with envoy - yorkie server with `gRPC error code 12 (unknown service)`
![캡처](https://user-images.githubusercontent.com/70474071/183495461-2a6709a7-43bd-48e3-8473-f290207d0ebc.JPG)

**What you expected to happen**:
Successful API call. (ex: Expected YORKIE I: [AC] c:"OOO" activated, id:"OOO")

**How to reproduce it (as minimally and precisely as possible)**:
1. Erase all yorkie server images on docker,
2. Run docker-compose file which contains yorkieteam/yorkie:lastest image and grpcweb:envoy image (getting latest version of yorkie)
3. send any request to envoy - yorkie server
4. receives gRPC error code 12 (unknown service)

**Anything else we need to know?**:
- Yorkie release version v0.2.14 works fine.
- Probably some change between `v0.2.14` and `v0.2.15` may have caused this error

**Environment**:
- Operating system: Windows 10, Mac OS Monterey, Amazon Linux 
- Browser and version: Chrome version 103.0.5060.134
- Yorkie version `v0.2.15`
- Yorkie JS SDK version: `v0.2.15`

**Comment by hackerwins** [comment]
Could you try updating the JS SDK to 0.2.15 on the web project causing the problem?

[v0.2.15](https://github.com/yorkie-team/yorkie/releases/tag/v0.2.15) broke backward compatibility, which seems to cause the problem.
(After the official release 1.x.x, we plan to manage the version)
