### ISSUE TITLE
Document watch/attach api slows down as document changes accumulate 

### ISSUE THREAD

**Issue by Krapi0314** [yorkie-team/yorkie#391]
**Description**:
Document watch/attach api slows down as document changes accumulate.

**Why**:
<img width="959" alt="Screen Shot 2022-08-10 at 1 35 17 PM" src="https://user-images.githubusercontent.com/70474071/183845811-73d02c21-6d3d-41d5-afa6-76201b8ba282.png">
- `watchDocuments` API took `1min ~ 3min` which makes yorkie document to load very slowly.
- This issue get worse as you make more changes on document.

**Comment by hackerwins** [comment]
The `WatchDocuments` API is used to establish a stream and send and receive events between a server and a client. Therefore, the response time can be over 1 minute.

However, it is strange that the response time of ListDocuments or other RPC APIs is slow in the log. 🤔 If there is a way to reproduce it, it would be helpful to find the cause.

**Comment by Krapi0314** [comment]
Sorry for late reply.

The only way to reproduce this is to constantly attach/detach **same** document, as far as I know.
As Room 1 on [demo.asyncrum.com](https://demo.asyncrum.com) shows, accessing same document over on over again makes document attachment slow.

Since [demo.asyncrum.com](https://demo.asyncrum.com) is using Yorkie SaaS, there will be informative logs on document in `Project=tldraw, Document Key=room1`. Please check those.

P.S: Will `attachDocument()` be effected on detaching docs/deactivating client?

**Comment by chromato99** [comment]
Hi. I'm interested in this issue, so I tried to write a simple test code once.
https://github.com/chromato99/yorkie/commit/b3bc6cfc048953f7ac8f18372d719ee7c5140353

When I tested with this simple test scenario, the result was as follows.
![Screenshot from 2022-10-24 20-37-05](https://user-images.githubusercontent.com/20539422/197518105-bd5f49c7-2be8-43b7-876c-635776103286.png)

I couldn't reproduce the situation in the above results..
It seems that the test scenario is too simple to reproduce the situation, but I would appreciate it if you could suggest a more suitable test scenario!

**Comment by Krapi0314** [comment]
Can you test your test code with no `detach()` scenario? I wonder how Yorkie Server will behave if `detach()` is excluded. This scenario may have occurred in my case, when the process is killed ungracefully.

**Comment by chromato99** [comment]
A warning that it is already attached appears, so I changed it to create a new client every time and tested it. https://github.com/chromato99/yorkie/commit/666d4ac1cbbc6bf10391e63932a98a12b2fe5017
The memory usage has increased significantly, but the time seems to have risen slightly compared to that.
![Screenshot from 2022-10-30 21-58-37](https://user-images.githubusercontent.com/20539422/198879808-3a82cdaf-a5dd-4e84-8a3d-2e327f57afcd.png)

In addition, I know that the housekeeping feature is deactivating clients that haven't been in use for a long time.
https://github.com/yorkie-team/yorkie/blob/89a2217549df1ba421816bf3c1b1be06c08d9aa7/server/backend/housekeeping/housekeeping.go#L17-L19

**Comment by Krapi0314** [comment]
Well, I see that the HouseKeeping Module is surely deactives inactive clients.

Maybe it's due to my Yorkie server cluster performance, since those servers were running on 2 instances of AWS EC2 T2.Micro. Single Yorkie couldn't keep up with my demo's traffic, so I clustered them. I reported this issue when I was using my own Yorkie server, so...

I think I should keep monitoring my yorkie-tldraw demo for a while, and see if any API network latency gets significantly slower  or not. Since it's using Yorkie SaaS, there will be no server performance issue.

Maybe it's just a normal behavior as people keep drawing and accumulating data on single doc...

**Comment by Krapi0314** [comment]
Okay, so the problem was actually on etcd in Yorkie Cluster mode.

The problem was that **etcd was not performing etcd log(key) compaction**, which made etcd perform slower due to log accumulation in etcd. Therefore yorkie sync method(API) was slowly takes longer as sync method call accumulates.

The solution for this problem is **etcd retentation log compaction**. This solution is suggested by @kpfaulkner, and this seems to minimize sync slowdowns. The test tool (https://github.com/kpfaulkner/yorkietest) is also provided by @kpfaulkner, and I did bulk update test for 20 docs with 1000 updates each.

Below this load test result **without etcd compaction configuration**, the average sync duration increased about 44ms per test. 
![etcd-compaction-off-test-1](https://user-images.githubusercontent.com/70474071/207060925-8e73dbd1-fe19-4ff6-9fa4-db76e130a344.PNG) ![etcd-compaction-off-test-2](https://user-images.githubusercontent.com/70474071/207060944-41205a25-fd1d-4bd5-a275-22947848a2f6.PNG) ![etcd-compaction-off-test-3](https://user-images.githubusercontent.com/70474071/207060950-6f9c9c73-0e4e-44bd-9d1c-a416d91bd32c.PNG)

Below this load test result **with etcd compaction configuration**, the average sync duration increased about 27ms per test. Also you can see the actual average sync duration is faster about 30ms then above.
![etcd-compaction-on-test-1](https://user-images.githubusercontent.com/70474071/207061447-af3a28a9-c5dc-4b2d-b2b6-477e7dcecca2.PNG) ![etcd-compaction-on-test-2](https://user-images.githubusercontent.com/70474071/207061452-004d709e-6e4b-45bc-b7c6-de9d44499bdb.PNG) ![etcd-compaction-on-test-3](https://user-images.githubusercontent.com/70474071/207061453-83ea2b00-2e91-4370-b670-2bce46f492b1.PNG)

This shows that the average latency improved about 38% (in later tests, I got 28%). Also I think the gap (average sync duration between the two) will dramatically grow as I test this with huge cluster & large test repetition.

And that it! So this problem can be solved by adding two more configuration flags
```yml
--auto-compaction-mode revision 
--auto-compaction-retention 1000
```

I think this is the problem of API getting slower, but there may be another reason. I think this configuration should be added in current Yorkie SaaS API backend, and see if this really works.

Thank you @kpfaulkner for problem/solution!

**Comment by hackerwins** [comment]
Thank you both for checking the issue. When applying cluster mode, I will refer to this.
