### ISSUE TITLE
Collect the client version and type that requested the API as a metric

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#393]
**Description**:

Collect the client version and type that requested the API as a metric.

We currently only released the [JS](https://github.com/yorkie-team/yorkie-js-sdk) and [Go SDK](https://github.com/yorkie-team/yorkie/tree/main/client). However, we plan to implement [Rust](https://github.com/yorkie-team/yorkie-rust-sdk) and [iOS](https://github.com/yorkie-team/yorkie-ios-sdk) and [Android](https://github.com/yorkie-team/yorkie-android-sdk) versions.

Let's monitor the usage by providing the version and type of the requested client as metrics.

**Why**:
- As the types and versions of clients increase, we can find out which clients are using the API.

**Comment by emplam27** [comment]
develop log link : https://codepair.navercorp.com/1si9dq
