### ISSUE TITLE
specify docker image version tag in docker compose 

### ISSUE THREAD

**Issue by Limm-jk** [yorkie-team/yorkie#403]
**Description**:

**Why**:
Latest tags are highly volatile. Therefore, the development environment may change depending on the time, developer by developer.

Specifying specific versions can prevent this side effect.

**Comment by Limm-jk** [comment]
If the maintainer agrees, I would like to change it to the current latest tag's version.

**Comment by hackerwins** [comment]
May I know which images you are suggesting to fix versions of?

**Comment by Limm-jk** [comment]
may be images in docker-compose-full.yaml? etcd, prometheus, etc...

**Comment by hackerwins** [comment]
I think it's ok to keep the latest version until we move to v1.0.0. When users officially use Yorkie next year, it would be better to fix them.
