### ISSUE TITLE
The project name is already in use when creating a new project

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#404]
**What happened**:

I have user A with a project named dev. 
If I try to create a new user B and a new project dev, I've got the error `The project name is already in use`.

**What you expected to happen**:

User B can create a project named dev.

**How to reproduce it (as minimally and precisely as possible)**:

1. Log in as user A 
2. Create project "dev"
3. Log in as user B 
4. Create project "dev"

**Anything else we need to know?**:

**Environment**:
- Operating system:
- Browser and version:
- Yorkie version (use `yorkie version`):
- Yorkie JS SDK version:

**Comment by jeonjonghyeok** [comment]
@hackerwins @chacha912  Could I try this issue?

**Comment by hackerwins** [comment]
@jeonjonghyeok Of course. Thank you for your interest.

**Comment by jeonjonghyeok** [comment]
> @jeonjonghyeok Of course. Thank you for your interest. It would be good to discuss some solutions before implementation.

@hackerwins I have now confirmed the changed message.
I've already worked on it, can I discuss it in PR? https://github.com/yorkie-team/yorkie/pull/406

**Comment by hackerwins** [comment]
This was fixed by https://github.com/yorkie-team/yorkie/pull/418.
