### ISSUE TITLE
Remove `Heap(Priority queue)` from `RHTPQMap`

### ISSUE THREAD

**Issue by hyeongsik-won** [yorkie-team/yorkie#423]
**What would you like to be added**:
We need to consider removing `Heap` from `RHTPQMap/elementQueueMapByKey`.

### Current
```swift
var elementQueueMapByKey: [String: Heap<TimeTicket, RHTPQMapNode>] = [:]
```

### Suggestion
```swift
var elementMapByKey: [String: (TimeTicket, RHTNode)] = [:]
```

**Why is this needed**:
`RHTPQMap` always uses the max value of `Heap`. We only need to hold the maximum value.

**Comment by blurfx** [comment]
I'm interested in this issue. Is there anything else we need to discuss or block?

**Comment by hackerwins** [comment]
Currently, each `key` in `Object` has a `MaxHeap` and the most recently set value is processed to be at the top. This can be considered a form of Tombstone, where deletion occurs but the element remains in memory to allow concurrent remote operations to be executed on it. However, this approach uses too much memory until the tombstone nodes are deleted by GC. Therefore, to reduce memory usage, we can remove the MaxHeap from Object and only keep the most recent node.

Caution:
If we remove tombstones from memory, it is possible that concurrent remote operations, executed locally, may encounter missing elements. It is important to check if exception handling is necessary for this scenario.

**Comment by blurfx** [comment]
resolved #462

**Comment by hackerwins** [comment]
I will open it again because it needs to be reflected in the iOS, JS, and Android SDKs.

**Comment by blurfx** [comment]
I would like to reflect this work in the JS SDK too, do I need to create a new issue in JS SDK, or can just comment here?

**Comment by hackerwins** [comment]
@blurfx You can just comment here. 👍
When creating a PR in the JS SDK, please refer to this issue.
