### ISSUE TITLE
Merging Text and RichText

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#435]
**Description**:

Merge `Text` and `RichText`. We also need to check the following:
- [x] Check if RichText is compatible with plain text-based editor examples and the existing data of CodePair.
- [x] If necessary, do migrate the existing data.

**Why**:

The reason for merging `Text` and `RichText` is that there might be too many data types if we added the [CRDT](https://crdt.tech/) for integration with ProseMirror and it could be confusing for users. And `Text` and `RichText` are similar, sequence-style data types.

```js
// Text
doc.update((root) => {
  root.text = new yorkie.Text(); // {"text":""}
  root.text.edit(0, 0, 'hello'); // {"text":"hello"}
  root.text.edit(0, 1, 'H');     // {"text":"Hello"}
  root.text.select(0, 1);        // {"text":"^H^ello"}
});

// RichText
doc.update((root) => {
  root.text = new yorkie.RichText();        // {"text":""}
  root.text.edit(0, 0, 'hello');            // {"text":"hello"}
  root.text.edit(0, 1, 'H');                // {"text":"Hello"}
  root.text.setStyle(0, 1, { bold: true }); // {"text":"<b>H</b>ello"}
});
```

**Comment by hackerwins** [comment]
After I started working on this, I was worried that the value of toJSON becomes more complex, even when the user only uses plain text. 🤔

```ts
const doc = new yorkie.Document<{
  contents: yorkie.Text;
}>();
// some updates...
console.log(doc.toJSON());

// AS-IS
{ contents: "hello world" }

// TO-BE
{ "contents": [{"attrs": {}, "value": "hello"}, {"attrs": {}, "value": "world"}] }
```

**Comment by humdrum** [comment]
We need to modify API too.

The difference between the two types has attributes or not.

1. RichTextNode, TextNode
https://github.com/yorkie-team/yorkie/blob/1216ad546a3b9e42b716dad3db0b2540767b60ef/api/yorkie/v1/resources.proto#L198-L217
3. TextEdit, RichTextEdit
https://github.com/yorkie-team/yorkie/blob/1216ad546a3b9e42b716dad3db0b2540767b60ef/api/yorkie/v1/resources.proto#L77-L99

Which work is better?

1. Remove the Text, the TextNode, and the TextEdit message. and link CRDTText(modified) to RichText.
  - Compatibility can be maintained.
2. Rename the RichText_xxx to Text_xxx.  
  - Break API Compatibility. But the source code can be clean.

**Comment by hackerwins** [comment]
@humdrum source of truth location of protobuf message is in [yorkie](https://github.com/yorkie-team/yorkie/tree/main/api/yorkie/v1).

It would be good to proceed with this task by recompiling after copying from Go.

**Comment by humdrum** [comment]
> @humdrum source of truth location of protobuf message is in [yorkie](https://github.com/yorkie-team/yorkie/tree/main/api/yorkie/v1).
> 
> It would be good to proceed with this task by recompiling after copying from Go.

I cited code from [yorkie](https://github.com/yorkie-team/yorkie/tree/main/api/yorkie/v1) too. ^^

**Comment by hackerwins** [comment]
I thought protobuf in iOS SDK was changed, because the [previous comment](https://github.com/yorkie-team/yorkie/issues/435#issuecomment-1379702173) referred to an older version of protobuf message.

As we merged the two text types, we made the following changes to the API. Protobuf messages were renamed because they ensure backwards compatibility as long as the order of the types is respected.

https://github.com/yorkie-team/yorkie/blob/6309915a54789958ada43d0dd54f4d86c2b9924e/api/yorkie/v1/resources.proto#L182-L194

https://github.com/yorkie-team/yorkie/blob/6309915a54789958ada43d0dd54f4d86c2b9924e/api/yorkie/v1/resources.proto#L77-L85

**Comment by humdrum** [comment]
In the resources.proto file, value type values are changed. Won't the API compatibility be broken?

<img width="1192" alt="스크린샷 2023-01-12 오전 11 53 18" src="https://user-images.githubusercontent.com/3667927/211964850-89118ad0-69c3-4d62-8272-ca99a9ea9b97.png">

@hackerwins

**Comment by hackerwins** [comment]
@humdrum There are no projects that use Counter yet, so we can change that.

**Comment by humdrum** [comment]
In resource.proto file, I found duplicated fields in TextNode and TextNodeAttr.

TextNode has an attributes map with a string key and a TextNodeAttr value. The key is one of the attribute names. (eg. bold, italic...)
And TextNodeAttr has a key field that has the same value as the key of the previous map.

Is there a case where the two values should be different?

https://github.com/yorkie-team/yorkie/blob/6309915a54789958ada43d0dd54f4d86c2b9924e/api/yorkie/v1/resources.proto#L182-L194

**Comment by hackerwins** [comment]
https://yorkie.dev/docs/js-sdk#text
