### ISSUE TITLE
Handle `JSON.parse` error properly

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#437]
**Description**:

When `JSON.parse` fails, an error that the document failed to load should be displayed.

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/81357083/209075597-c217c77b-f59b-4745-be73-f8c03947bd6a.png">

An error occurs when accessing the `examples$20221216` document in the default project from the admin account.
https://yorkie.dev/dashboard/projects/default/documents/examples$20221216

**Why**:
If only an empty screen is displayed, users don't know why the page is not working.

**Comment by cozitive** [comment]
Fixed by #443
