### ISSUE TITLE
Improving documentation for developers

### ISSUE THREAD

**Issue by cozitive** [yorkie-team/yorkie#450]
**Description**:
- [x] Organize environment setting process and contribution flow
- [x] Provide direct access to design documents in contributing docs
- [x] Provide table of contents of design docs and a brief description of each document
- [x] Move [garbage collection](https://yorkie.dev/docs/internals#garbage-collection) description to design documents in GitHub repo
- [ ] Add reference guides (ex. creating a new data type)

**Why**:
Design documents, providing detailed information of how Yorkie works, have low accessibility now. There are no introduction about the documents, and some contents (ex. [garbage collection](https://yorkie.dev/docs/internals#garbage-collection)) are even out of GitHub `design` directory.

**Comment by hackerwins** [comment]
Since writing the 5th guide for creating new data types is more difficult than the others, it would be better to move the garbage collection description to the design document and close this issue.
