### ISSUE TITLE
Supper OrbitDB/SkyBase

### ISSUE THREAD

**Issue by TheRook** [yorkie-team/yorkie#460]
**What would you like to be added**:
Consider using https://github.com/berty/go-orbit-db as a backend to expose yorkie as a Kademlia service.  Kademlia implemented with libp2p is one of the most mature p2p networks, designed over 20 years ago it has scaled up to hundreds of millions of nodes and is the network behind Ethereum, IPFS and Magnet BitTorrent links.

**Why is this needed**:
It allows yorkie to be run as a federated dapp and hosted by a community.
https://www.youtube.com/watch?v=cC-tXnMyiBc

https://github.com/artflake/SkyBase

**Comment by hackerwins** [comment]
Thanks for your reporting.

Currently, I don't feel the need to support OrbitDB. I'll consider reopening this issue when needed.
