### ISSUE TITLE
Document/Client data is not cleared at detachment/deactivation

### ISSUE THREAD

**Issue by cozitive** [yorkie-team/yorkie#465]
**Description**:
In Yorkie server, document detachment and client deactivation do not clear relevant data in DB:  `ClientInfo.ClientDocInfo` and `ClientInfo`, respectively.

**`ClientDocInfo` is not cleared after a document is detached**

Document detachment just converts `ClientDocInfo`'s status to `DocumentDetached`, not removing unused data.

https://github.com/yorkie-team/yorkie/blob/fde366b2fd962f9f016e5f6021c53a02912e997b/server/backend/database/client_info.go#L118-L130

**`ClientInfo` is not cleared after a client is deactivated**

`ClientInfo` is just changing its status to `ClientDeactivated`, not being deleted.

- MemDB

https://github.com/yorkie-team/yorkie/blob/fde366b2fd962f9f016e5f6021c53a02912e997b/server/backend/database/memory/database.go#L432

https://github.com/yorkie-team/yorkie/blob/fde366b2fd962f9f016e5f6021c53a02912e997b/server/backend/database/client_info.go#L88-L92

- MongoDB

https://github.com/yorkie-team/yorkie/blob/fde366b2fd962f9f016e5f6021c53a02912e997b/server/backend/database/mongo/client.go#L490-L498

**Why**:
- If a client repeats document attachment and detachment, a number of redundant `ClientDocInfo`s will be created; these unused data will occupy DB storage.
- Unused deactivated `ClientInfo` and relevant `ClientDocInfo`s will accumulate in the DB.

**Comment by hackerwins** [comment]
We use soft delete strategy for resources. Comparing soft deletion and hard deletion, there are the following differences:

## A. Soft Delete

It means marking data as deleted without actually removing it from DB.

Pros:
- It makes easy data recovery and maintains deletion history
- It also prevents accidental data loss.

Cons:
- It makes DB size keeps growing and may slow down queries.
- It requires care with privacy regulations.

## B. Hard Delete:

It deletes completely removes data from DB

Pros:
- It makes efficient database size management and better performance.
- It makes easy to compliance with privacy regulations.

Cons:
- It makes difficulty to recover deleted data and risk of accidental data loss.
- It also makes hard to track data history.

So it is recommended to use soft deletion for important business data and hard deletion for less important data. It would be good to use soft deletion for now and let's consider to minimize storage costs later.
