### ISSUE TITLE
Add logout command to CLI

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#488]
**Description**:

We can log in to the Yorkie server, to use admin APIs which can manage documents and projects with CLI.

```sh
$ yorkie login -u username -p password
$ yorkie project ls

 NAME     PUBLIC KEY            SECRET KEY            AUTH WEBHOOK URL  AUTH WEBHOOK METHODS  CREATED AT
 default  cg044avhiqss73d20n2g  cg044avhiqss73d20n30                    []                    6 days
```

But we don't have logout command to log out from the Yorkie server yet.

Refer to:
  - docker login: https://docs.docker.com/engine/reference/commandline/login/
  - docker logout: https://docs.docker.com/engine/reference/commandline/logout/
  - https://github.com/yorkie-team/yorkie/issues/377

Related to #544

**Why**:
- The user can use the logout command to delete authentication information locally.

**Comment by blurfx** [comment]
I'm interested in this issue. can I work on it?

**Comment by hackerwins** [comment]
Thank you for your research.

Instead of token invalidation, I think deleting the token from the context file(`~/.yorkie/config.json`) would be a more appropriate way to handle the logout command for now.

It might be beneficial to consider aspects such as token invalidation for future reference as well.
