### ISSUE TITLE
Cleanup protobuf response

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#498]
**Description**:

Remove unnecessary client information from the protobuf response.

We are currently returning `client_id` or `client_key` as follows:
https://github.com/yorkie-team/yorkie/blob/main/api/yorkie/v1/yorkie.proto#L41-L116

```
message ActivateClientResponse {
  string client_key = 1;
  bytes client_id = 2;
}

message DeactivateClientResponse {
  bytes client_id = 1;
}

message AttachDocumentResponse {
  bytes client_id = 1;
  string document_id = 2;
  ChangePack change_pack = 3;
}

message DetachDocumentResponse {
  string client_key = 1;
  ChangePack change_pack = 2;
}

message RemoveDocumentResponse {
  string client_key = 1;
  ChangePack change_pack = 2;
}

message PushPullChangesResponse {
  bytes client_id = 1;
  ChangePack change_pack = 2;
}
```

We only need to return the `client_id` when activating, and the rest seems unnecessary. 
It would be better to clean up.

**Why**:
to make protobuf concise

**Comment by hackerwins** [comment]
# Tasks
- [x] Go SDK: https://github.com/yorkie-team/yorkie/pull/614
- [x] JS SDK: https://github.com/yorkie-team/yorkie-js-sdk/pull/617
- [ ] Android SDK:
- [ ] iOS SDK:
