### ISSUE TITLE
The CONTRIBUTING.md doesn't contain latest changes.

### ISSUE THREAD

**Issue by maruldy** [yorkie-team/yorkie#510]
**Description**:
I read [CONTRIBUTING.md](https://github.com/yorkie-team/yorkie/blob/main/CONTRIBUTING.md) to contribute to this project, and found an error for this document. 
[Building & Testing]((https://github.com/yorkie-team/yorkie/blob/main/CONTRIBUTING.md#building--testing)) section about setting up a test-environment using docker-compose, which should have been updated after merging this commit : https://github.com/yorkie-team/yorkie/commit/d8625cdad83fc2b6907a9abc747ab91c48ff1cf4

**Why**:
Anyone would be confused to prepare contribution for yorkie.

**Comment by krapie** [comment]
Oops, I missed that one, thank you!
