### ISSUE TITLE
Cache ProjectInfo to Improve Overall RPC Response Time

### ISSUE THREAD

**Issue by krapie** [yorkie-team/yorkie#568]
**Description**:

Cache `ProjectInfo` to improve overall RPC response time.

**Why**:

Every time RPC is called, `buildContext()` in the RPC interceptor is called before the RPC handler to build context data, which includes project metadata for RPC.

https://github.com/yorkie-team/yorkie/blob/aa2f3618f8fc0a53cfdca6717b37a6dfa1eeadd0/server/rpc/interceptors/context.go#L153

Currently, `ProjectInfo` is queried from DB every time when `buildContext()` is called. And it is inefficient to query the same data every time the RPC is called.

By introducing caching for `ProjectInfo`, we can dramatically improve query time for building context data, resulting faster RPC response time.

**Comment by blurfx** [comment]
I'll work on it
