### ISSUE TITLE
Garbage collection for Text and RichText

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#58]
In issue #3, we have implemented Garbage Collection for child elements of Container such as Array and Object.

https://github.com/yorkie-team/yorkie/blob/master/pkg/document/json/root.go#L94

Text and Rich Text use RgaTreeSplit and may have removed TextNodes inside Although they are not Container. We need the Garbage Collection of this removed TextNodes.

https://github.com/yorkie-team/yorkie/blob/master/pkg/document/json/rga_tree_split.go#L225

**Comment by dc7303** [comment]
Could I try this issue?

**Comment by hackerwins** [comment]
@dc7303 Sure.
