### ISSUE TITLE
Replace Text.select with Presence

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#583]
**Description**:

Recently we introduced batch updates of documents and presences to provide atomic change delivery and events from `document.subscribe`. All operations and presence changes created in `document.update` guarantee atomic delivery, So we can replace `Text.select` with presence and delete the method for now.

```ts
// Before
doc.update((root) => {
  root.text = new yorkie.Text();            // {"text":""}
  root.text.edit(0, 0, 'hello');            // {"text":"hello"}
  root.text.select(0, 1);                   // {"text":"^h^ello"}
});

// After
doc.update((root, presence) => {
  root.text = new yorkie.Text();                          // {"text":""}
  root.text.edit(0, 0, 'hello');                          // {"text":"hello"}
  presence.set('selection', root.text.createRange(0, 1)); // {"text":"^h^ello"}
});
```

We need to do the below:

- [x] Provide `Text.createRange`
- [x] Replace `Text.select` with presence in all Text examples
- [x] Remove `Select` operation from `Text`

Batch updates of documents and presences:
- Server and Go SDK: https://github.com/yorkie-team/yorkie/pull/582
- JS SDK: https://github.com/yorkie-team/yorkie-js-sdk/pull/574

**Why**:
- Clean up unnecessary features to keep the product simple.

**Comment by joonhyukchoi** [comment]
I'm interested in this issue. can i work on it?

**Comment by krapie** [comment]
@joonhyukchoi let's give it a try!

**Comment by chacha912** [comment]
@joonhyukchoi  Yes. When making that changes to protobuf, there can be compatibility issues with previous versions. In such cases, we have been labeling issues and PRs with `protocol changed📝` to indicate the compatibility impact.
(Since there have been no real production yet, we have been working on it with breaking version compatibility.)

**Comment by joonhyukchoi** [comment]
@chacha912 Thank you. I'll follow that!

**Comment by hackerwins** [comment]
Tasks:

- [x] Go SDK: https://github.com/yorkie-team/yorkie/pull/589
- [ ] JS SDK:
- [ ] Android SDK:
- [ ] iOS SDK:

**Comment by blurfx** [comment]
I'll work on the js sdk
