### ISSUE TITLE
Atomicity not guaranteed when using BulkWrite

### ISSUE THREAD

**Issue by fourjae** [yorkie-team/yorkie#588]
**Description**:

Atomicity must be guaranteed when performing bulk updates using 'bulkwrite' in mongodb.

**Why**:

https://github.com/yorkie-team/yorkie/blob/1b557be51471337d3c6949d5f9ed5634b3a677e2/server/backend/database/mongo/client.go#L888

There is no guarantee of atomicity when using bulkWrite.

Transactions are required when processing many operations. However, this causes performance problems.
Which method should I use?

references:

- [To make the BulkWrite operation atomic, use Transactions.](https://www.mongodb.com/community/forums/t/bulkwrite-on-single-document-acid/117330)

**Comment by hackerwins** [comment]
@fourjae 

Yorkie Server follows a specific approach when editing a Document.

It first stores all the changes that occur during `document editing` in the `changes` collection. Then it stores the last change to `server_seq` in the "documents" collection. This storage process does not execute queries into transactions, to reduce the load on the database.

Even if the storage process encounters failures, the `server_seq` stored in the `documents` collection remains unaffected. When other requests attempt to load changes or save further changes, they operate based on `server_seq` in the `documents` collection. If necessary, these requests may overwrite the `changes`.
