### ISSUE TITLE
JS SDK v0.4.5 causing excessive WatchDocument requests and server v0.4.4 instability

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#590]
**Description**:

JS SDK v0.4.5 causing excessive WatchDocument requests and server v0.4.4 instability

Recently, we released JS SDK v0.4.5, but we haven't deployed Server v0.4.5 to  https://api.yorkie.dev/ yet. Due to a protocol change in v0.4.5, it is incompatible with Server v0.4.4.

When attempting to use JS SDK v0.4.5 with Server v0.4.4, the client starts generating an overwhelming number of WatchDocument requests, leading to server instability that resembles a DDOS attack.

<img width="718" alt="Screenshot 2023-07-27 at 5 46 19 PM" src="https://github.com/yorkie-team/yorkie/assets/2059311/822e1986-ec03-4428-a7d2-481cb1eed527">

**Why**:

We need to address this issue urgently to ensure smooth communication between JS SDK and the server while maintaining stability and compatibility.

**Comment by g2hhh2ee** [comment]
Sorry about that. It wasn't a DDos attack and I think it was my fault.

I created a new yorkie example around 3:00 on the 27th and ran it locally with yorkie-js-sdk v.0.4.5. 
As soon as I ran the project with the new version, it kept sending requests to the server. I freaked out, stopped and ran it again, and the same thing happened, so I captured it.

**Comment by dc7303** [comment]
It may be possible to respond at the infrastructure layer to defend against DDOS, but I think it is necessary to respond at the application level before that. How about introducing RateLimit?

**Comment by hackerwins** [comment]
I think we can introduce rate limits in a couple of places:

A. K8s Ingress

We can utilize rate limit annotations for a straightforward implementation. However, it's important to note that this approach offers global-wide options, which might limit flexibility.

B. API Server

To have more granular control, we can implement rate limit logic using a gRPC interceptor. This approach allows us to define detailed rate limit rules. Additionally, we could provide project-specific options in the dashboard, empowering developers to manage rate limits for their projects effectively.

**Comment by krapie** [comment]
@hackerwins Since we are using Istio in K8s, we can use Istio(envoy)'s [Rate Limit](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/). 

For implementation details, we use istio-ingressgateway as a rate limiter middleware by applying the rate limit configuration envoyfilter, and [rate limiting service](https://github.com/envoyproxy/ratelimit) as a rate limit counter.

**Comment by joonhyukchoi** [comment]
I want to try this issue!

**Comment by krapie** [comment]
@joonhyukchoi Sure! If you are going to implement rate limiter on K8s with Istio, this will help.

> Since we are using Istio in K8s, we can use Istio(envoy)'s [Rate Limit](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/). 

> For implementation details, we use istio-ingressgateway as a rate limiter middleware by applying the rate limit configuration envoyfilter, and [rate limiting service](https://github.com/envoyproxy/ratelimit) as a rate limit counter.
