### ISSUE TITLE
Remove obsolete clients

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#61]
Obsolete clients are clients that will not be used again. If the client's last access time is older than a certain threshold, we can determine whether it is obsolete or not. The threshold may vary by applications or services, so it should be set as an option by the user.

The reasons for deleting obsolete clients are:
 - We can prevent the `clients` collection from growing
 - If a document is attached by the obsolete client, we cannot purge removed elements that didn't pull by the obsolete client in the garbage collection

Relevant ticket: #3

**Comment by codinggosu** [comment]
I'd like to take a look at this issue
