### ISSUE TITLE
Change 'Documents' from plural to singular in DocEvent

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#612]
**Description**:

Change "documents" to "document" in DocEvent (since the WatchDocument API has been updated to operate on a single document: https://github.com/yorkie-team/yorkie-js-sdk/pull/480).

Related: https://github.com/yorkie-team/yorkie/pull/609

**Why**: Cleanup DocEvent

**Comment by hackerwins** [comment]
@chacha912 Do we need to apply this update to other SDKs?

**Comment by chacha912** [comment]
@hackerwins  Yes, due to a protocol change, modifications are required in other SDKs as well.

**Comment by hackerwins** [comment]
Tasks:
- [x] Go SDK: https://github.com/yorkie-team/yorkie/pull/613
- [ ] JS SDK:
- [ ] Android SDK:
- [ ] iOS SDK:

**Comment by hackerwins** [comment]
@chacha912 How about doing #498 together?
