### ISSUE TITLE
Add Tree.Edit benchmark

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#623]
**Description**:

Recently, Yorkie provides Tree for WYSIWYG editors that have a tree-based model. Let's add benchmarks of Tree to track its performance.

Tree specifications:
- https://github.com/yorkie-team/yorkie/blob/main/test/integration/tree_test.go

Similar issues:
- https://github.com/yorkie-team/yorkie/issues/600
- https://github.com/yorkie-team/yorkie/issues/180
- https://github.com/yorkie-team/yorkie/issues/251

**Why**:

It is important to track performance when adding new features or methods because Tree is a data structure and sometimes users may load a lot of data to it.

**Comment by JOOHOJANG** [comment]
It would be nice for a new contributor to do it, but I think I should do it right away because it's related to the work I'm doing right now. Can I take it?

**Comment by hackerwins** [comment]
@JOOHOJANG Sure, give it a try.
