### ISSUE TITLE
Add toJS to return TreeNode of Tree

### ISSUE THREAD

**Issue by JOOHOJANG** [yorkie-team/yorkie#632]
**What would you like to be added**:
Restore `iterator` inside `Tree`

**Why is this needed**:
During the 0.4.6 release process, I removed `iterator` from `JSON/CRDT Tree` because there's no need to remain linked-list and list-related logics inside the `Tree`. Also, we still can access Tree data by using `toJSON()` method. 
However, it was created for testing purposes (serialize data unnecessarily), so I'm trying to restore `iterator` inside `Tree`

**Comment by hackerwins** [comment]
SDKs:

- [ ] JS SDK: https://github.com/yorkie-team/yorkie-js-sdk/pull/639
- [ ] Android SDK:
- [ ] iOS SDK:
