### ISSUE TITLE
Tree.edit performance improvements

### ISSUE THREAD

**Issue by JOOHOJANG** [yorkie-team/yorkie#635]
**What would you like to be added**:
Creating a data structure to compute segment sums of left siblings.

**Why is this needed**:
While I'm working on add benchmark test(https://github.com/yorkie-team/yorkie/issues/623), I found out there's a critical performance issue. 
The main reason is converting CRDTTreeNode to corresponding index/path takes very long time, because it's **linearly** adding left siblings.

Therefore, I think new data structure/algorithm is needed to address the shortcomings of the current Tree.

1. Prefix Sum
    - o(1) for query
    - o(n) for update
    - o(n) for insert/delete
    
2. AVL Tree(RB, LLRB, OST)
    - o(logn) for query
    - o(logn) for update
    - o(logn) for insert/delete
    
3. BIT(Fenwick Tree)
    - o(logn) for query
    - o(logn) for update
    - o(n) for insert/delete
    

When considering the characteristics, update will rarely takes place while insert/delete happens a lot.
While the AVL Tree appears to be the most suitable, it has the disadvantage of consuming more memory than Prefix Sum and Fenwick/Segment Tree, because it has to maintaining link. Also, Fenwick tree is optimized for calculating segment sums. Thus, even at the same O(logn), they outperform AVL trees in range queries.

So, I'm going to test both the AVL Tree and the Fenwick Tree to determine which one is more suitable for our use case.

### FYI) 밀리초 is equals to ms
**100 TreeNodes**
<img width="565" alt="treePosToPath" src="https://github.com/yorkie-team/yorkie/assets/46807540/d914da71-0135-46a1-9311-2aa7c31d08dc">

**200 TreeNodes**
<img width="637" alt="traverselnPosRange" src="https://github.com/yorkie-team/yorkie/assets/46807540/1c4d5b4b-42c1-4d38-a281-a8d67bd831c5">

**300 TreeNodes**
<img width="641" alt="treePosToPath tolndex" src="https://github.com/yorkie-team/yorkie/assets/46807540/cc41a068-8a74-49e7-9475-86406c041dc0">

**400 TreeNodes**
<img width="698" alt="treePosToPath" src="https://github.com/yorkie-team/yorkie/assets/46807540/036c2a91-a373-498f-8a53-7eeea022cb0c">

**800 TreeNodes**
<img width="748" alt="toindex" src="https://github.com/yorkie-team/yorkie/assets/46807540/7dde5b98-8b95-4b50-890f-17535c505883">

**1000 TreeNodes**
<img width="385" alt="tolhdex" src="https://github.com/yorkie-team/yorkie/assets/46807540/96b5d061-8fbc-41cd-8aef-b899fc8c0af4">

**Comment by JOOHOJANG** [comment]
Significant performance improvements were achieved through tuning, not by applying algorithms.(Thanks to @hackerwins )
However, I will keep this issue open because it needs to be improved.

**Comment by hackerwins** [comment]
I'll close this issue for now. Let's open a new one when we make further improvements.
