### ISSUE TITLE
Clarify the usage of the term `peer`

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#665]
**Description**:

The term `peer` generally does not include oneself. However, in the context of Yorkie, the word `peer` is used to refer to other clients, including the current one. To avoid confusion, ensure that the term `peer` is consistently used to represent other clients, and when referring to both peers and oneself, use terms like `users` or `clients`. (It is also required in the examples)

**Why**: Clarify the usage of the term `peer`

**Comment by hackerwins** [comment]
The term `Peer` can be found in the examples and documentation, but it does not appear to be used in source code. So, I'll close this issue for now.

<img width="690" alt="Screenshot 2024-07-23 at 2 16 46 PM" src="https://github.com/user-attachments/assets/26704ada-7736-4eca-ae4d-3f7dffa40a56">
