### ISSUE TITLE
request: write contribution.md 

### ISSUE THREAD

**Issue by computerphilosopher** [yorkie-team/yorkie#68]
There is no contribution guideline yet, so we'd better make it.

Example: When committing a new code, write the test code together.

**Comment by hackerwins** [comment]
Thanks for the good comments. Do you have any examples to look at and follow along?

**Comment by dc7303** [comment]
In the long term, the kind of SDK will increase.
So I think it's worth considering the `mattermost` [contribution guide](https://github.com/mattermost/mattermost-server/blob/master/CONTRIBUTING.md).

**Comment by dc7303** [comment]
There is a simpler template, so I share it.
[https://github.com/nhn/tui.editor/blob/master/CONTRIBUTING.md](https://github.com/nhn/tui.editor/blob/master/CONTRIBUTING.md)

**Comment by hackerwins** [comment]
@dc7303 
The TUI Editor's contribution guide seems to be simple and well documented. Hopefully, we start in a similar way.
