### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by ppeeou** [yorkie-team/yorkie#69]
yorkie version 0.0.9 -> 0.0.10

Existing working examples are not working since this commit.
https://github.com/yorkie-team/yorkie/commit/75b448fe9899d7526e2cf27e5b779fbcc06a1469

**Comment by hackerwins** [comment]
@ppeeou Thanks for reporting.
Does the example of yorkie-js-sdk fail in the local environment?
If so, please check the Yorkie version.
```
$ docker exec -it yorkie bash -c "./bin/yorkie version"
Yorkie: 0.0.10
Commit: f07b15e
Go: go1.14.4
```

**Comment by ppeeou** [comment]
@hackerwins I wrote it too vaguely..!  I mean, When an event occurs, synchronization with other clients is not performed immediately.
 It is detailed in this issue. https://github.com/yorkie-team/yorkie-js-sdk/issues/48

**Comment by ppeeou** [comment]
@hackerwins oh .. Both yorkie-sdk-js and yorkie use the current version and it works fine.
