### ISSUE TITLE
Where is updatedAt used?

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#70]
While implementing Increase operation(#12), I became curious about the `updatedAt` property of data type in json package.

I expected this for this property. For example, 
```go
err := doc.Update(func(root *proxy.ObjectProxy) error {
			root.SetNewText("k1")
				.Edit(0, 0, "ABCD")
			text := root.GetText("k1")
			u := text.UpdatedAt()
			assert.NotNil(t, u)
			return nil
	})
```

As in this example, I thought that `updatedAt` would be modified when a modification occurs, but `updatedAt` is `nil`.  
And I looked for where the `UpdateAt()` and `SetUpdatedAt()` methods are used, but I couldn't find them.

Is this missing implementation? Or am I wrong about `updatedAt`?

**Comment by hackerwins** [comment]
@dc7303 Thank you for reporting.
`updatedAt` is used to indicate that the relative position of the element has changed by `move` in the array, not the value change. Well, the name `updatedAt` is common, so I think it needs to be changed.

**Comment by dc7303** [comment]
@hackerwins I think I can proceed. I think `movedAt`, what do you think?    
If not Is there a name you are thinking of? If yes, can you please suggest?

**Comment by hackerwins** [comment]
movedAt seems good. 😄

**Comment by daclouds** [comment]
Could I try this issue?

**Comment by hackerwins** [comment]
Sure. :)
