### ISSUE TITLE
Suggestion for support flutter

### ISSUE THREAD

**Issue by ymw0407** [yorkie-team/yorkie#704]
**What would you like to be added**:  
If what I know is true, Yorkie project is available on JS, Android, iOS only. And I know that it is not yet supported for Windows, Linux, and macOS, but it would be nice if it could be used in various environments through Flutter.

**Why is this needed**: 
to support various environments.

It would be great if there was any intention to support these desktop apps as well!

**Comment by hackerwins** [comment]
There are no plans to support flutter yet. I'll close this issue for now.
