### ISSUE TITLE
Need an issue template

### ISSUE THREAD

**Issue by ppeeou** [yorkie-team/yorkie#72]
yorkie also needs an issue template.
like [ISSUE_TEMPLATE](https://github.com/yorkie-team/yorkie-js-sdk/tree/master/.github/ISSUE_TEMPLATE)

Could I make it the same as  [yorkie-js-sdk](https://github.com/yorkie-team/yorkie-js-sdk)

**Comment by hackerwins** [comment]
Sure. 😃
