### ISSUE TITLE
Introduce Prometheus metrics

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#76]
Yorkie is getting more complex as features are added. So, we need to monitor the status of Agent.
It would be nice to support Prometheus `/metrics` and monitor them in yorkie.dev.

- ETCD: https://github.com/etcd-io/etcd/blob/master/etcdserver/metrics.go

**Comment by daclouds** [comment]
Could I try this issue?

before I start, I have a question.
Is there any custom application-specific metrics we need?
(In the example of etcd, custom metrics related to leader are registered.)

**Comment by hackerwins** [comment]
@daclouds Sure. Thank you for your interest in this issue.

I think We need to record snapshot related metrics.
- Yorkie: https://github.com/yorkie-team/yorkie/blob/master/yorkie/packs/pack_service.go#L119
- ETCD: https://github.com/etcd-io/etcd/commit/67645095e902beb11de34d7317ffbb0eb49e1b4b#diff-4e0502c268b93a783e61e10d1ac1cb99R104-R108

Also, I think It would be nice to save the basics at the beginning of the work(e.g. `currentVersion`, `currentGoVersion`).
