### ISSUE TITLE
Error in concurrent editing and styling (Edit+Style) handling

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#788]
**Description**:

        
**What happened**:
Refer to #780 , there is an error occurring in the concurrent editing and styling (Edit+Style) handling. Failure cases related to Style operation are as follows:

  - Edit and Style (15/84 cases)
    - (6) {equal, equal-multiple} / {insert-front, insert-middle, replace} / style
    - (4) {intersect, A -> B} / {insert-middle, insert-back} / style
    - (1) A contains B / insert-middle / style
    - (4) B contains A / {insert-front, insert-middle, insert-back, replace} / style

  - Split and Edit (46/144 cases)
    - (2) A contains B / {split-1, split-2} / {style, remove-style}
    - (2) B contains A / {split-1, split-2} / {style}
    - (1) B contains A / split-2 / remove-style
    - (8) {right node text, right node element} / {split-1, split-2} / {style, remove-style}
    - (2) A -> B / {split-1, split-2} / {style}
    - (1) A -> B / split-2 / remove-style

**What you expected to happen**:
The concurrent editing and styling (Edit+Style) should work without any errors.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce the issue, follow the steps:
1. Differentiate between nodes that have been newly inserted and existing nodes during the concurrent editing and styling process by comparing `Node.CreatedAt` and `editedAt` timeTicket.
2. The style operation is ignored for nodes created before concurrency edit.

**Anything else we need to know?**:
The error appears to be related to the violation of the commutative property.

**Comment by raararaara** [comment]
<img width="837" alt="image" src="https://github.com/yorkie-team/yorkie/assets/31478163/81449755-a979-448b-bb14-bc3170311cde">
