### ISSUE TITLE
Add ConnectRPC Spec Definition for API Documentation

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/yorkie#804]
**What would you like to be added**:

With the introduction of ConnectPRC, allowing REST API calls, it is necessary to document the specification.
Using methods like OpenAPI to define the spec would enable the use of convenient GUI tools like Swagger.

Tools like [`protoc-gen-connect-openapi`](https://github.com/sudorandom/protoc-gen-connect-openapi) can automatically generate OpenAPI documentation from proto files.

The execution result is as shown below.
<img width="1471" alt="image" src="https://github.com/yorkie-team/yorkie/assets/52884648/046a8477-1b4b-4f69-aca3-be6224e403a9">
<img width="1471" alt="image" src="https://github.com/yorkie-team/yorkie/assets/52884648/5ce291ff-0c69-4695-b34a-27debb6c94ec">

This will not only benefit REST API users but also aid in API development.

**Why is this needed**:

Documenting the ConnectRPC specification will provide better understanding and usability of the API, benefiting both users and developers alike.

**Comment by krapie** [comment]
We might want to add this to our documentation for API usage 👍🏼

**Comment by devleejb** [comment]
@krapie
Does the documentation mean [Yorkie Docs](https://yorkie.dev/docs), right?

**Comment by krapie** [comment]
@devleejb Yes, just like Firebase.

![Screenshot 2024-03-04 at 8 20 39 PM](https://github.com/yorkie-team/yorkie/assets/70474071/dff57727-21b8-4eb5-8110-bdb0dcf61369)

**Comment by hackerwins** [comment]
We can also refer to the following:
- https://liveblocks.io/docs/api-reference/rest-api-endpoints
- https://supabase.com/docs/guides/api#api-url-and-keys

**Comment by devleejb** [comment]
Can I try it?

**Comment by hackerwins** [comment]
@devleejb Sure. You're a maintainer of this project.

**Comment by devleejb** [comment]
I've made the modifications in `buf.gen.yaml`:

```yaml
version: v1
plugins:
  - plugin: go
    out: api
    opt: paths=source_relative
  - plugin: connect-go
    out: api
    opt: paths=source_relative
  - plugin: connect-openapi
    out: api/docs
    opt:
      - base=api/docs/yorkie.base.yaml
```

The generated OpenAPI Spec can be served using the Swagger UI container, and I've added the corresponding command to the Makefile:

```Makefile
docker-swagger:
	docker run -p 3000:8080 \
  		-e URLS="[ \
			{ url: 'docs/yorkie/v1/admin.openapi.yaml', name: 'Admin' }, \
			{ url: 'docs/yorkie/v1/resources.openapi.yaml', name: 'Resources' }, \
			{ url: 'docs/yorkie/v1/yorkie.openapi.yaml', name: 'Yorkie' }  \
		]" \
		-v `pwd`/api/docs:/usr/share/nginx/html/docs/ \
  		swaggerapi/swagger-ui
```

As a result, when accessing the served documents, they will be displayed as shown in the image below:

![image](https://codepair-api.yorkie.dev/files/devleejb-5y4bxp.png)

However, adding the Authentication option in the `connect-openapi` library causes an error. I have reported this issue to the library's repository and will create a PR after resolving it.
[Link to the GitHub Issue](https://github.com/sudorandom/protoc-gen-connect-openapi/issues/5)

After incorporating these changes, the following updates are required for the Yorkie Document:

- [ ] List additional endpoints to be added to the document.
- [ ] Write markdown documentation based on the OpenAPI Spec (considering automation).
