### ISSUE TITLE
Include yorkie-mongodb to yorkie-cluster Helm Chart

### ISSUE THREAD

**Issue by krapie** [yorkie-team/yorkie#819]
**Description**:

Include `yorkie-mongodb` to `yorkie-cluster` Helm chart as subchart.

Recently we have removed mongoDB subchart in `yorkie-cluster` while introducing `yorkie-mongodb`. Because of this, we now need to install both `yorkie-cluster` and `yorkie-mongodb` to fully setup Yorkie cluster, which is a bit cumbersome.

- https://github.com/yorkie-team/yorkie/pull/769

**Why**:

To fully provide Yorkie cluster feature including DB layer when installing `yorkie-cluster` Helm chart.

**Comment by hyun98** [comment]
@krapie Hi, Can I try this issue? :)

**Comment by krapie** [comment]
@hyun98 Sure! We need to think about how to gracefully add mongoDB into Yorkie cluster.

I think there can be several approaches, such as options to select between standalone or sharded mongoDB. Or we can introduce new full version of Yorkie server system Helm chart that contains all components of Yorkie cluster.

**Comment by krapie** [comment]
@hyun98 Thank you for your deep investigation!

> So, I brought the entire mongodb-sharded chart and tried to modify and use only the mongodb-sharded.configServer.primaryHost part, and I checked the successful operation during the minikube test.

So we need to leverage customized `mongodb-sharded` chart to integrate with `yorkie-cluster` chart?

> I don't think it looks good to show in the 'CrashLoopBackOff' state, so I'm thinking about whether need the yorkie pods's waiting job.

How about using [initContainer](https://kubernetes.io/ko/docs/concepts/workloads/pods/init-containers/) in Kubernetes to make Yorkie server pod wait MongoDB pods to be ready?

**Comment by hyun98** [comment]
First, I tested the stable installation of yorkie-cluster using initContainer. thank you @krapie 

Currently, mongodb-sharded charts seem difficult to use as subcharts. So, I have raised an issue with bitnami/mongodb-sharded.

It seems that the way of importing the entire mongodb-sharded chart and modifying only part of it is not good for maintenance. 
Whereas, it seems best to merge my PR in the bitmani chart and upload the chart version. But the downside is that I don't know when my PR will be merged.

Therefore.. how about putting this issue on hold for a while?

**Comment by hyun98** [comment]
@krapie
The [PR I posted on mongodb-sharded](https://github.com/bitnami/charts/pull/29145) has been merged, and if we use `mongodb-sharded` chart version `8.3.7` or higher, we will be able to use the `mongodb-sharded` chart without any namespace issues.
