### ISSUE TITLE
Improve Sync method of Client

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie#87]
While analyzing the code, I noticed that the `Sync` method of `Client` works synchronously inside a loop.  
I thought if sync method work asynchronously, it will work much faster.

So I tested it through a prototype. [(Link)](https://github.com/dc7303/yorkie/commit/464cf04aa761ec6743643f4dadcde3027609d36d)  
And through this test, it showed more than 3 times higher performance when operated asynchronously.  
[(Test Code)](https://github.com/dc7303/yorkie/commit/464cf04aa761ec6743643f4dadcde3027609d36d)
```bash
## Deliberately manipulated the test failure to view the log.
## It is not affecting the current test cases.

--- FAIL: TestClientAndDocument (8.87s)
    --- FAIL: TestClientAndDocument/Synchronous_and_asynchronous_performance_comparison_of_Sync_method_test (0.47s)
        client_test.go:913: Async : 83606000 nanosecond
        client_test.go:921: Sync : 286075000 nanosecond
        client_test.go:922: 
                Error Trace:    client_test.go:922
                Error:          Not equal: 
                                expected: true
                                actual  : false

```
However, I am not sure if it is safe to operate asynchronously.
What do you think about this? I need advice.

**Comment by hackerwins** [comment]
@dc7303 

We haven't started optimizing for cases where a client has attached multiple documents yet. And I am concerned that the code will be complicated to handle asynchronously. For now, It would be good to postpone optimization then consider optimization when a situation arises where users use Go Client.

**Comment by dc7303** [comment]
@hackerwins 
Thank you for your advice :)

**Comment by hackerwins** [comment]
It would be nice to reopen later. Close this issue for now.
