### ISSUE TITLE
Show Server Version in Yorkie CLI

### ISSUE THREAD

**Issue by krapie** [yorkie-team/yorkie#870]
**Description**:

Add the functionality to display the server version in Yorkie CLI alongside the existing information about the Yorkie client version and so on.

```bash
$ yorkie version
Yorkie: 0.4.0
Commit: 782f93d
Go: go1.20.4
Build date: 2023-06-05
```
[kubectl](https://kubernetes.io/docs/reference/kubectl/) shows bellow information including server version which kubectl is currently targeting.

```bash
$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

**Why**:

Having the ability to see the server version directly in the Yorkie CLI helps users easily track the server version they are interacting with, providing crucial information for debugging and maintenance purposes.

**Comment by hyun98** [comment]
HI :) I'm interested in working on this issue. Could I take on this issue?

**Comment by krapie** [comment]
@hyun98 Sure! I think referencing kubectl's code will help implementing this feature.
