### ISSUE TITLE
Update Document updatedAt to only include Document.Root modifications 

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#916]
**Description**:

Currently, modification to `Document.Presence` updates the Document's updatedAt, even if there are no changes to `Document.Root` content. This behavior can lead to unnecessary `updatedAt` updates and may not accurately reflect the actual content changes.

**Why**:

**Comment by krapie** [comment]
@binary-ho Sure! I think you will need basic understanding of document editing in Yorkie :)

**Comment by window9u** [comment]
Hello!

I'm interested in working on this issue. Could I take on this issue?

**Comment by krapie** [comment]
@window9u Sure! No problem. I think this issue is related to CRDT operation, so it will be good to get more context from the community.
