### ISSUE TITLE
Implement DB Query for GetDocuments API to improve performance

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#921]
**What would you like to be added**:

Recently, GetDocuments API was added as a bulk version of the GetDocument API to retrieve multiple documents at once. However, the necessary DB Query for the GetDocuments API has not been implemented yet. It is crucial to implement a database query that can retrieve multiple documents at once to improve performance.

https://github.com/yorkie-team/yorkie/blob/28ef053a5af5a53c2af1d0e043240adc62be1701/server/documents/documents.go#L130-L148

- https://github.com/yorkie-team/yorkie/pull/909
- https://github.com/yorkie-team/codepair/issues/173

**Why is this needed**:

To enhance performance by efficiently retrieving multiple documents with a single query from the database.

**Comment by kokodak** [comment]
May I try this issue?

**Comment by sejongk** [comment]
> May I try this issue?

Of course. If you have any question, feel free to ask.

**Comment by krapie** [comment]
@devleejb I recall that you have the context about this issue. Is there any context or discord discussion related to this issue?

**Comment by devleejb** [comment]
> @devleejb I recall that you have the context about this issue regarding CodePair. Is there any context or discord discussion related to this issue?

Sure.

Recently, we changed from calling the GetDocument API multiple times to calling the GetDocuments API once in CodePair. Despite this, there has not been a significant improvement in response time.

The reason is that it is implemented to call GetDocumentSummary multiple times while iterating over the given keys.

Once we resolve this issue, we expect the document loading speed in CodePair to be much faster.

**Comment by kokodak** [comment]
Is the problem caused by fewer API calls, but not less DB access via single retrieval queries?

If so, can I solve the issue by preparing queries that can get multiple results in a single query, such as bulk operations?

**Comment by devleejb** [comment]
@kokodak 
> Is the problem caused by fewer API calls, but not less DB access via single retrieval queries?
I didn't fully understand what this means.

> If so, can I solve the issue by preparing queries that can get multiple results in a single query, such as bulk operations?
I think this method can solve the issue."

**Comment by kokodak** [comment]
> I didn't fully understand what this means.

What I meant was that although it reduced the number of API calls by combining multiple `GetDocument API` calls into a single `GetDocuments API` call, it seems that the actual implementation of the `GetDocuments API` is still issuing multiple single queries for documents.

I'll try to resolve the issue in the direction mentioned above. Thanks!

**Comment by hackerwins** [comment]
Before (1.01s):
<img width="1278" alt="Screenshot 2024-07-20 at 1 57 52 AM" src="https://github.com/user-attachments/assets/8fa3da3f-5d78-44fa-bcc7-d1cdcab5a69b">

https://codepair.yorkie.dev/community

**Comment by hackerwins** [comment]
After (72ms):
<img width="1300" alt="Screenshot 2024-07-25 at 4 07 26 PM" src="https://github.com/user-attachments/assets/2bf89de2-0639-4505-b393-5329e2b51b55">
