### ISSUE TITLE
Provide a notification when client is deactivated due to housekeeping

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#928]
**Description**:

When a client leaves a document without properly deactivating(detaching), it remains as a zombie client, leading to inefficiencies in garbage collection. To address this issue, server deactivates clients that have been inactive for a certain period through a [housekeeping process](https://github.com/yorkie-team/yorkie/blob/main/design/housekeeping.md).

The [default Client Deactivate Threshold](https://github.com/yorkie-team/yorkie/blob/24950f554c2ab6f2b58e55d2172b310f4e6cd20f/server/config.go#L57) is set to 24 hours, meaning that if a client has not edited the document for 24 hours, it will be deactivated and no longer considered to be participating in document editing.

However, there are cases where a user leaves a document open for a long time without actively editing it, causing housekeeping to occur and disconnecting the user from document editing. In such cases, users should be notified that the document has been disconnected and instructed to re-attach in order to continue editing.

**Considerations**:
- Check for any unpushed local changes before deactivating the client
- Ensure proper handling of the deactivated client in garbage collection

**Comment by hackerwins** [comment]
Flow for Deactivation of Outdated Clients by housekeeping:

A. Initial Setup
- Subscribe to Document.Subscribe('status') event: yorkie-team/yorkie-js-sdk#828

B. Server-side Housekeeping Processing
- Client Deactivation triggered by Housekeeping
- Detach Attachment(#907)

C. Client Re-access
- Request initiated by SyncLoop or WatchLoop
- Server replies ErrClientDeactivated to the client: #927

D. Client-side Handling
- Receive ErrClientDeactivated error
- Pass Detached event to Document.Subscribe

E. Required User Actions
- E1. Reconnection
  - Create new Client and Document
  - Reestablish attachment using newly created objects (similar to page reload)
- E2. Data Preservation
  - Potential loss of unsent Local Changes
  - Recommended providing Copy & Paste UI(similar to Copy & Paste UI of Google Docs, https://github.com/yorkie-team/yorkie/issues/52#issuecomment-1044039394)
