### ISSUE TITLE
Error occurs when executing `FindDocInfosByKeys` query with empty docKeys argument

### ISSUE THREAD

**Issue by raararaara** [yorkie-team/yorkie#943]
**What happened**:
When performing the `FindDocInfosByKeys` query with an empty array for docKeys, the server encounters a critical issue. Specifically, the server crashes with the following error:
```
2024-07-26T01:27:13.710+0900    WARN    a16     RPC : "/yorkie.v1.AdminService/GetDocuments" 
1.773583ms: &{"project_name:\"default\"" {'\x00' "/yorkie.v1.AdminService/GetDocuments" 
%!q(bool=false) '\x00'} {"[::1]:49484" "connect" map[]} map["Authorization":
["cqh6cnh97i624rnkavk0"] "Content-Length":["70"] "Content-Type":["application/json"] "Host":
["localhost:8080"]] "POST"} => "find documents: (BadValue) $in needs an array"
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Execute the `FindDocInfosByKeys` query with an empty array for docKeys.
2. Observe the server crashing and generating the mentioned error.

**Anything else we need to know?**:

**Environment**:
- Operating system:
- Browser and version:
- Yorkie version (use `yorkie version`): v0.4.28
- Yorkie JS SDK version:

**Comment by raararaara** [comment]
cc @blurfx

**Comment by blurfx** [comment]
Unhashable errors are not going to have a common interface, so it's probably better to handle panic in that context with `recover`.

Considering just `mongo` for example, `mongo.CommandError` and `mongo.WriteError`, `mongo.WriteException`, and `mongo.BulkWriteException` do not have a common field, so interface checking is not possible.
