### ISSUE TITLE
CI workflow doesn't work due to Docker Compose V1 being deprecated on the runner's ubuntu image

### ISSUE THREAD

**Issue by kokodak** [yorkie-team/yorkie#949]
**What happened**:

Since [this PR](https://github.com/actions/runner-images/pull/10368), docker compose V1 no longer works with ubuntu images in the actions runner.
For this reason, there is currently an issue with CI workflow not working properly.

<img width="902" alt="image" src="https://github.com/user-attachments/assets/983d8486-4005-4d24-ab62-04eca0f252f2">

**What you expected to happen**:

The CI workflow should work correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Refer to the [Docker documentation for Migrate Compose V2](https://docs.docker.com/compose/migrate/), replacing the commands in compose V1 with the commands in compose V2.

**Anything else we need to know?**:

This issue can occur in multiple repositories within yorkie-team, not just the yorkie repository.

**Environment**:
- Operating system:
- Browser and version:
- Yorkie version (use `yorkie version`): v0.4.28
- Yorkie JS SDK version:

**Comment by krapie** [comment]
Is this issue occurring every time we perform `docker-compose` command on Github Actions?
I think we need to find which repositories are using `docker-compose` command and make a checklist below to track it.

**Comment by kokodak** [comment]
> Is this issue occurring every time we perform `docker-compose` command on Github Actions? I think we need to find which repositories are using `docker-compose` command and make a checklist below to track it.

In Github Actions, yes.

Elsewhere, Compose V1 will work, but Docker compose V1 will be deprecated after 2021, so it's probably best to move to Compose V2 in most cases.

The only place I've found that uses docker-compose is the [ci.yaml in yorkie-js-sdk](https://github.com/yorkie-team/yorkie-js-sdk/blob/ae7461b2a4203e3906be32f7189cee96c066a5cb/.github/workflows/ci.yml).

**Comment by kokodak** [comment]
Some of the documentation points to using docker-compose, do we need to change that?

**Comment by krapie** [comment]
@kokodak Yes. I think it is time to update everything to docker compose V2.

**Comment by fourjae** [comment]
In #950 PR, the main CONTRIBUTING.md and docker README.md files were modified. Is there anything else that needs to be modified?

**Comment by krapie** [comment]
@fourjae I think yorkie repository is up to date. I have checked the occurrence of the word `docker-compose -f`.
Could you re-check it to see if there are anything that we have omitted?

**Comment by kokodak** [comment]
I will work on the Compose V1 issue in the yorkie-js-sdk repository.

**Comment by fourjae** [comment]
@krapie 
I think the docker-compose -f command no longer exists in all files of the yorkie server project.
