### ISSUE TITLE
Provide global output flag for setting output format in CLI commands

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#955]
**Description**:

Recently, we added the `output` flag to the `version` command in the CLI to specify the output format (`''`, `yaml`, `json`). This format allows users to configure their system workflows when invoking the CLI, making it easier for the system to recognize the data.

https://github.com/yorkie-team/yorkie/pull/938

Currently, the `output` flag is specific to the `version` command, but it can be expanded to serve the purpose of specifying the output format for all CLI commands.

**Why**:

To provide a consistent and convenient way for users to set the output format for all CLI commands, enhancing the usability of the CLI tool.

**Comment by TaeyeonRoyce** [comment]
Hi, Can I handle this issue?

**Comment by hackerwins** [comment]
@TaeyeonRoyce Sure. 👍
