### ISSUE TITLE
Set updatedAt value for newly created documents

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#968]
**What happened**:

When creating a new document through the dashboard example, the `updatedAt` value is not displaying correctly in the document list. (Ref: https://github.com/yorkie-team/dashboard/issues/99)

**What you expected to happen**:

When a document is first created, the `updatedAt` should be set to the same value as `createdAt`.
Reasons for this approach:
1. Initial state indication: It clearly shows that the record has not been modified since its creation.
2. Data consistency: All records will have an `updatedAt` value from the moment of creation.
 
**How to reproduce it (as minimally and precisely as possible)**:

1. Navigate to the dashboard
2. Create a new document using the provided example
![image](https://github.com/user-attachments/assets/9b3a2a6a-aa91-4660-9a75-7952daa3809e)
3. Check the document list
![image](https://github.com/user-attachments/assets/7ddea883-46be-461b-9046-00adf0542b7a)
4. Observe that the `updatedAt` value is not correctly set

**Anything else we need to know?**:

**Environment**:
- Operating system:
- Browser and version:
- Yorkie version (use `yorkie version`): 0.4.30
- Yorkie JS SDK version: 0.4.28

**Comment by window9u** [comment]
Hello! I've identified an issue that needs fixing:

While working on [this pull request](https://github.com/yorkie-team/yorkie/pull/935), I realized that `updated_at` is only being updated when there's an `operation` in `Change`. This explains why `updatedAt` isn't set when a document is created.

I apologize for my mistake and will fix it immediately.

**Comment by hackerwins** [comment]
@window9u There's no need to be sorry. It seems natural that bugs are created due to changes. I'll wait for your PR.
