### ISSUE TITLE
Modify to use default values ​​when there is no metrics field in config

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#97]
We recently added a feature to serve [Prometheus metrics](https://github.com/yorkie-team/yorkie/issues/76). If there is no metrics field in the config after this commit, we are getting the error below.

``` json
{
  "RPC": {
    "Port": 9090,
    "CertFile": "",
    "KeyFile": ""
  },
  "Mongo": {
    "ConnectionTimeoutSec": 5,
    "ConnectionURI": "mongodb://localhost:27017",
    "YorkieDatabase": "yorkie-meta",
    "PingTimeoutSec": 5
  },
  "Backend": {
    "SnapshotThreshold": 500
  }
}
```

![image](https://user-images.githubusercontent.com/2059311/95671225-34fc0700-0bcf-11eb-8aff-9efb0263a050.png)

If the user doesn't specify the metrics field, we can handle it in one of two ways to avoid errors.
- Run the metrics handler with the default port value
- Do not execute metrics handler

**Comment by daclouds** [comment]
Could I try this issue?
