### ISSUE TITLE
Add Account Deletion and Password Change to CLI Commands

### ISSUE THREAD

**Issue by chacha912** [yorkie-team/yorkie#982]
**What would you like to be added**:

Currently, our CLI supports login and logout commands:
https://yorkie.dev/docs/cli#login

```
$ yorkie login -u <username> -p <password> --rpc-addr api.yorkie.dev:443
$ yorkie logout
```

With the recent development of `ChangePassword` and `DeleteAccount` APIs on the server side(#849), we should extend our CLI functionality to include these features.

Implementation Details
- Integrate with the newly developed server APIs: `ChangePassword` and `DeleteAccount`.
- Implement proper error handling and user feedback.
- Ensure secure handling of sensitive information (passwords).
- Update CLI documentation to reflect these new commands.

Security Considerations
- For the delete account command, consider implementing a confirmation step to prevent accidental deletions.
- Ensure all communications with the server for these sensitive operations are properly encrypted.

**Why is this needed**:

CLI users can manage their accounts without switching to a different interface, streamlining their workflow.

**Comment by krapie** [comment]
Currently, account deletion does not performing cascading deletion over associated resources.
Is it okay to provide deletion to the users right now?
