### ISSUE TITLE
Provide a way to refresh token for Auth Webhook

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie#996]
**Description**:

We have added the auth webhook feature in #188, which allows the `Client` to verify whether it has access rights to a specific `Document`. The current implementation only utilizes the initially provided token for authentication, and there is no functionality for **token refresh once it expires**.

```
(5) response the request  (4) handle the request
     ┌─────────────────┐  ┌──┐
     │                 │  │  │   (3) response
     ▼                 │  ▼  │    - allowed
 ┌──────┐             ┌┴─────┤    - reason   ┌──────────────┐
 │Client├────────────►│Server│◄──────────────┤Outside Server│
 └──────┘ (1)request  └────┬─┘               └──────────────┘
           - token         │                      ▲
           - dockey        └──────────────────────┘
                               (2) call webhook
                                - token
                                - dockey
                                - verb: r or rw
```

- https://yorkie.dev/docs/cli#auth-webhook

To enhance the user experience, I propose implementing a token refresh mechanism. This would involve two key components:
- **A. Server**: After calling the Auth Webhook, if the token has expired, it should notify the Client of the token expiration.
- **B. Client**: Upon receiving the expiration event from the Server, the Client should provide an interface that allows the injection of a refreshed token (similar to an auth callback).

Related to https://github.com/yorkie-team/yorkie/pull/188#issuecomment-847481195
Related to https://github.com/yorkie-team/codepair/issues/160

**Why**:

Implementing this token refresh mechanism will ensure that users can maintain their sessions without interruptions, thereby providing a seamless and continuous experience while working with the Client.

**Comment by krapie** [comment]
@xet-a Seems like this issue is somewhat similar to your previous refresh token work on CodePair?

**Comment by xet-a** [comment]
I'm interested in this issue. Can I try this?

**Comment by krapie** [comment]
@xet-a Assigned 😄
